/**
 * Host-side container config for the `codex` provider.
 *
 * Codex reads auth and MCP config from ~/.codex. We give each session its
 * own private copy of that directory. Host coupling is CREDENTIAL-ONLY:
 *
 * - auth.json comes from the per-group `~/.codex-<folder>/` when present,
 *   else the shared-account `~/.codex/auth.json` — the same scoped-override /
 *   shared-fallback semantics as Claude's .env token resolution.
 * - config.toml is GENERATED (buildContainerCodexConfig). The host's own
 *   config.toml never reaches a container: it carries host-personal state
 *   (model default, personality, the projects trust table, TUI/hook state)
 *   that is meaningless or leaky in-container. The in-container runtime
 *   appends MCP server blocks and writes hooks.json on every spawn
 *   (codex-app-server.ts), and per-query model/effort arrive via -c from
 *   container.json providerConfig.
 * - agents/ named-role definitions come from the GROUP-OWNED
 *   `groups/<folder>/.codex/agents/` (tracked in the groups repo, parallel
 *   to `.claude/agents/*.md`), populated by `src/codex-sync.ts`. There is
 *   deliberately NO fallback to any host `~/.codex*` agents dir.
 *
 * Env passthrough covers the two knobs that are read at runtime:
 *   OPENAI_API_KEY  — fallback auth when auth.json isn't a subscription token
 *   CODEX_MODEL     — model override if the user wants something other than the default
 *   OPENAI_BASE_URL — rare, but supports API-compatible alternates
 */
import fs from 'fs';
import os from 'os';
import path from 'path';

import {
  assertRealDirectory,
  removeUntrustedPathEntry,
  replaceUntrustedDirectory,
  replaceUntrustedFile,
  resolveContainedRealDirectory,
} from '../fs-safety.js';
import { assertValidGroupFolder } from '../group-folder.js';
import { registerProviderContainerConfig, type VolumeMount } from './provider-container-registry.js';

function resolveCodexSourceDir(agentGroupFolder: string | undefined, agentGroupId: string, hostHome: string): string {
  const scopedFolder = agentGroupFolder || agentGroupId;
  // Defense-in-depth — same rationale as resolveOpenCodeSourceDir in opencode.ts.
  assertValidGroupFolder(scopedFolder);
  const scoped = path.join(hostHome, `.codex-${scopedFolder}`);
  if (fs.existsSync(path.join(scoped, 'auth.json'))) return scoped;
  return path.join(hostHome, '.codex');
}

/** Container working roots that codex should treat as trusted projects. */
const CONTAINER_TRUSTED_PROJECTS = ['/workspace/agent', '/workspace/workgroup', '/workspace/worktrees', '/tmp'];

/**
 * Container-owned base config.toml. Every setting a container needs is
 * declared here explicitly — nothing is inherited from the host CLI's
 * config. The values mirror what the fleet has always effectively run with;
 * [features] is load-bearing (hooks = the destructive-action guard chain,
 * multi_agent_v2 = native subagents, memories/goals = their MCP surfaces).
 */
export function buildContainerCodexConfig(): string {
  return [
    '# Generated by NanoClaw (src/providers/codex.ts) — container-owned.',
    '# Rewritten on every spawn; the in-container runtime appends MCP blocks.',
    'sandbox_mode = "workspace-write"',
    'approval_policy = "on-request"',
    'approvals_reviewer = "auto_review"',
    '',
    '[features]',
    'hooks = true',
    'remote_control = true',
    'memories = true',
    'goals = true',
    '',
    '[features.multi_agent_v2]',
    'enabled = true',
    'max_concurrent_threads_per_session = 9',
    '',
    ...CONTAINER_TRUSTED_PROJECTS.flatMap((proj) => [`[projects."${proj}"]`, 'trust_level = "trusted"', '']),
  ].join('\n');
}

registerProviderContainerConfig('codex', (ctx) => {
  const codexDir = path.join(ctx.sessionDir, 'codex');
  fs.mkdirSync(codexDir, { recursive: true });
  assertRealDirectory(codexDir);
  // The plugin cache is derived exclusively from `/workspace/plugins`.
  // Rebuild it on every container spawn so an unchanged plugin version cannot
  // leave stale bytes in a long-lived session directory.
  removeUntrustedPathEntry(codexDir, 'plugins');
  // Remove the top-level derived temp entry, not `.tmp/marketplaces`: `.tmp`
  // was container-writable and could otherwise redirect host cleanup through
  // a planted intermediate symlink.
  removeUntrustedPathEntry(codexDir, '.tmp');
  const mounts: VolumeMount[] = [{ hostPath: codexDir, containerPath: '/home/node/.codex', readonly: false }];

  // Credential-only host read: auth.json from the per-group Codex home when
  // present (`~/.codex-<folder>/auth.json`), otherwise the shared-account
  // fallback `~/.codex/auth.json`. Nothing else is sourced from host homes.
  const hostHome = ctx.hostEnv.HOME || os.homedir();
  let authContents: Buffer | null = null;
  if (hostHome) {
    const sourceDir = resolveCodexSourceDir(ctx.agentGroupFolder, ctx.agentGroupId, hostHome);
    const hostAuth = path.join(sourceDir, 'auth.json');
    if (fs.existsSync(hostAuth)) {
      authContents = fs.readFileSync(hostAuth);
    }
  }
  const configContents = buildContainerCodexConfig();

  // agents/: named subagent role definitions ([agents.*] roles read from
  // $CODEX_HOME/agents/*.toml). Group-owned: `groups/<folder>/.codex/agents/`,
  // written by `src/codex-sync.ts` (managed roster) plus any hand-authored
  // role tomls (e.g. a QA worker), tracked in the groups repo exactly like
  // `.claude/agents/*.md`. Mount RO (definitions are read-only to Codex;
  // keeps host re-syncs live and prevents the container from mutating defs).
  // Deliberately no fallback to `~/.codex*` — host CLI config must never
  // shape a container agent.
  const groupAgents = path.join(ctx.groupDir, '.codex', 'agents');
  const groupAgentsEntry = fs.lstatSync(groupAgents, { throwIfNoEntry: false });
  const agentsDir = groupAgentsEntry ? resolveContainedRealDirectory(ctx.groupDir, '.codex', 'agents') : null;

  // Every generated entry may have been replaced while the prior container
  // owned this RW mount. Recreate them without following prior symlinks.
  if (authContents) replaceUntrustedFile(codexDir, 'auth.json', authContents);
  else removeUntrustedPathEntry(codexDir, 'auth.json');
  replaceUntrustedFile(codexDir, 'config.toml', configContents);
  removeUntrustedPathEntry(codexDir, 'agents');
  if (agentsDir) {
    replaceUntrustedDirectory(codexDir, 'agents');
    mounts.push({
      hostPath: agentsDir,
      containerPath: '/home/node/.codex/agents',
      readonly: true,
      // groupDir is agent-writable. Reuse the runner's just-before-Docker
      // realpath check so a post-validation swap aborts instead of escaping.
      overlayAllowedRoots: [fs.realpathSync(ctx.groupDir)],
    });
  }

  const env: Record<string, string> = {};
  for (const key of ['OPENAI_API_KEY', 'CODEX_MODEL', 'OPENAI_BASE_URL'] as const) {
    const value = ctx.hostEnv[key];
    if (value) env[key] = value;
  }

  return {
    mounts,
    env,
  };
});
