/**
 * Host-side container config for the `codex` provider. Each session gets a private ~/.codex; host coupling is
 * CREDENTIAL-ONLY. auth.json comes from `~/.codex-<folder>/` when present, else `~/.codex/`. config.toml is GENERATED:
 * the host's own carries host-personal state (trust table, TUI and hook state) that is meaningless or leaky in a
 * container. agents/ comes only from the group-owned `groups/<folder>/.codex/agents/`, with deliberately NO fallback
 * to a host `~/.codex*` dir.
 */
import fs from 'fs';
import os from 'os';
import path from 'path';

import {
  assertRealDirectory,
  removeUntrustedPathEntry,
  replaceUntrustedDirectory,
  replaceUntrustedFile,
  resolveContainedRealDirectory,
} from '../fs-safety.js';
import { assertValidGroupFolder } from '../group-folder.js';
import { registerProviderContainerConfig, type VolumeMount } from './provider-container-registry.js';

function resolveCodexSourceDir(agentGroupFolder: string | undefined, agentGroupId: string, hostHome: string): string {
  const scopedFolder = agentGroupFolder || agentGroupId;
  // folder/id reaches path.join, so traversal is rejected before the scoped path is formed.
  assertValidGroupFolder(scopedFolder);
  const scoped = path.join(hostHome, `.codex-${scopedFolder}`);
  if (fs.existsSync(path.join(scoped, 'auth.json'))) return scoped;
  return path.join(hostHome, '.codex');
}

const CONTAINER_TRUSTED_PROJECTS = ['/workspace/agent', '/workspace/workgroup', '/workspace/worktrees', '/tmp'];

/**
 * Container-owned base config.toml: every setting is declared here, nothing is inherited from the host CLI.
 * [features] is load-bearing (hooks = the destructive-action guard chain, multi_agent = native subagents,
 * memories/goals = their MCP surfaces).
 */
export function buildContainerCodexConfig(): string {
  return [
    '# Generated by NanoClaw (src/providers/codex.ts) — container-owned.',
    '# Rewritten on every spawn; the in-container runtime appends MCP blocks.',
    'sandbox_mode = "workspace-write"',
    'approval_policy = "on-request"',
    'approvals_reviewer = "auto_review"',
    'model_context_window = 400000',
    'model_auto_compact_token_limit = 360000',
    '',
    '[features]',
    'context_management = true',
    'hooks = true',
    'fast_mode = false',
    'memories = true',
    'goals = true',
    'multi_agent = true',
    '',
    '[agents]',
    // No `default_subagent_reasoning_effort`, on purpose: a subagent inherits its spawner's effort unless the spawn or
    // its ROLE sets one, and each `/orchestrate` shim's role pins its own level.
    // Byte-identical with CONTAINER_CODEX_CONFIG_BASE in container/agent-runner/src/codex-companion-setup.ts
    // (src/provider-surfaces.test.ts).
    'max_concurrent_threads_per_session = 5',
    '',
    ...CONTAINER_TRUSTED_PROJECTS.flatMap((proj) => [`[projects."${proj}"]`, 'trust_level = "trusted"', '']),
  ].join('\n');
}

registerProviderContainerConfig('codex', (ctx) => {
  const codexDir = path.join(ctx.sessionDir, 'codex');
  fs.mkdirSync(codexDir, { recursive: true });
  assertRealDirectory(codexDir);
  // Rebuilt on every spawn so an unchanged plugin version cannot leave stale bytes in a long-lived session dir.
  removeUntrustedPathEntry(codexDir, 'plugins');
  // The top-level `.tmp`, not `.tmp/marketplaces`: `.tmp` was container-writable and could redirect host cleanup
  // through a planted intermediate symlink.
  removeUntrustedPathEntry(codexDir, '.tmp');
  const mounts: VolumeMount[] = [{ hostPath: codexDir, containerPath: '/home/node/.codex', readonly: false }];

  const hostHome = ctx.hostEnv.HOME || os.homedir();
  let authContents: Buffer | null = null;
  if (hostHome) {
    const sourceDir = resolveCodexSourceDir(ctx.agentGroupFolder, ctx.agentGroupId, hostHome);
    const hostAuth = path.join(sourceDir, 'auth.json');
    if (fs.existsSync(hostAuth)) {
      authContents = fs.readFileSync(hostAuth);
    }
  }
  const configContents = buildContainerCodexConfig();

  // Mounted RO so the container cannot mutate role definitions and host re-syncs stay live. Deliberately no fallback
  // to `~/.codex*`: host CLI config must never shape a container agent.
  const groupAgents = path.join(ctx.groupDir, '.codex', 'agents');
  const groupAgentsEntry = fs.lstatSync(groupAgents, { throwIfNoEntry: false });
  const agentsDir = groupAgentsEntry ? resolveContainedRealDirectory(ctx.groupDir, '.codex', 'agents') : null;

  // Every generated entry may have been replaced while the prior container owned this RW mount, so each is recreated
  // without following prior symlinks.
  if (authContents) replaceUntrustedFile(codexDir, 'auth.json', authContents);
  else removeUntrustedPathEntry(codexDir, 'auth.json');
  replaceUntrustedFile(codexDir, 'config.toml', configContents);
  removeUntrustedPathEntry(codexDir, 'agents');
  if (agentsDir) {
    replaceUntrustedDirectory(codexDir, 'agents');
    mounts.push({
      hostPath: agentsDir,
      containerPath: '/home/node/.codex/agents',
      readonly: true,
      // groupDir is agent-writable: the runner's just-before-Docker realpath check aborts a post-validation swap.
      overlayAllowedRoots: [fs.realpathSync(ctx.groupDir)],
    });
  }

  const env: Record<string, string> = {};
  for (const key of ['OPENAI_API_KEY', 'CODEX_MODEL', 'OPENAI_BASE_URL'] as const) {
    const value = ctx.hostEnv[key];
    if (value) env[key] = value;
  }

  return {
    mounts,
    env,
  };
});
