/**
 * Container-local CODEX_HOME setup.
 *
 * When Claude is the agent provider but the agent invokes Codex as a peer
 * (via the `/codex:rescue` subagent or the codex-companion script bundled
 * in the `~/plugins/codex/` plugin), the spawned `codex` reads MCP servers
 * from `~/.codex/config.toml`. Inside the container `~/.codex/` is a staged
 * session-local home whose `config.toml` the host regenerates on every spawn
 * (`stageCodexAuth`, src/container-runner.ts), so an MCP entry written there
 * would not survive — and it carries no MCP servers to begin with.
 *
 * The fix: synthesize a container-only Codex config directory at
 * `/home/node/.codex-runtime/`, populated with:
 *   - a symlink to `~/.codex/auth.json`, itself a file-bind of the host home's
 *     auth.json (so OAuth refresh still persists back to the host) — the ONLY
 *     thing this container reads from `~/.codex`
 *   - a GENERATED config.toml (CONTAINER_CODEX_CONFIG_BASE) plus exactly the
 *     MCP servers the agent-runner has wired (including `nanoclaw`)
 *   - an `agents/` symlink to the group-owned roster at
 *     `/workspace/agent/.codex/agents` (written by src/codex-sync.ts)
 *   - a container-owned Codex plugin registration built fresh from
 *     `/workspace/plugins` (see `registerContainerCodexPlugins`)
 *
 * Containers must have ZERO dependency on host CLI state. The host's
 * config.toml, MCP server tables, agents/ dir, and plugin caches are never
 * read — host coupling is credential-only (auth.json), mirroring the
 * provider=codex path (src/providers/codex.ts).
 *
 * The agent-runner sets `process.env.CODEX_HOME` to this directory before
 * constructing the provider — `env: { ...process.env }` is snapshotted into
 * the provider's spawn-env, and inherited by every subsequent `node`,
 * `bun`, or `codex` child process.
 *
 * No-ops when:
 *   - the codex auth mount is absent (the group withholds the `codex` plugin,
 *     which is the only thing that mount now rides on)
 *   - we're already inside a Codex-provider session (Codex's own writer
 *     handles `~/.codex/config.toml` directly)
 */
import { spawnSync, type SpawnSyncReturns } from 'node:child_process';
import fs from 'fs';
import path from 'path';

import { loadExcludedPlugins } from './excluded-plugins.js';
import { isExcludedPluginPath, type ExcludedPlugins } from './plugin-exclusions.js';
import {
  readCodexConfigToml,
  writeCodexConfigToml,
  writeCodexConfigTomlAsserting,
} from './providers/codex-config-file.js';
import {
  type AppServer,
  buildCodexHooksJson,
  listCodexHooks,
  parseTomlTableHeader,
  renderCodexMcpServer,
  writeCodexHooksJson,
} from './providers/codex-app-server.js';
import {
  type CodexHookTrustEntry,
  classifyCodexHookList,
  collectCodexHookTrustEntries,
  codexHookTrustTables,
  collectPluginHookTrustEntries,
  formatCodexHookTrustProblem,
  mergeCodexHookTrustIntoToml,
} from './providers/codex-hook-trust.js';
import {
  type AgentRuntime,
  type DiscoveredSkill,
  discoverPortableSkills,
  readPluginDenySiblings,
  syncSkillSymlinks as syncDiscoveredSkillSymlinks,
} from './plugin-skill-discovery.js';
import type { McpServerConfig } from './providers/types.js';

/**
 * Re-exported from its owning module so the historical import path keeps
 * working; `providers/codex-config-file.ts` is where the three-answer read and
 * the durable commit live, shared with `providers/codex-app-server.ts`.
 */
export { readCodexConfigToml };

const HOST_CODEX_DIR = '/home/node/.codex';
const RUNTIME_CODEX_DIR = '/home/node/.codex-runtime';
/**
 * Deliberately nonexistent path. Handed out as CODEX_HOME when the real runtime
 * dir could not be built — codex refuses to start rather than falling back to
 * the default home ("Error finding codex home: CODEX_HOME points to ..., but
 * that path does not exist"), which is exactly the fail-closed property we want.
 * Named so it self-documents in `printenv` and in a log line.
 */
const FAILED_CODEX_HOME = '/nonexistent/codex-runtime-setup-failed';
const CONTAINER_CLAUDE_SKILLS_DIR = '/home/node/.claude/skills';
const CONTAINER_PLUGINS_DIR = '/workspace/plugins';
// Runtime-agnostic skill discovery path. Codex auto-scans this in addition
// to $CODEX_HOME/skills/ — verified empirically via `codex debug
// prompt-input` (~/.agents/skills/ appears as discovery root `r1`).
// Other compliant agent runtimes (OpenCode, etc.) read here too.
const CONTAINER_AGENTS_SKILLS_DIR = '/home/node/.agents/skills';

/**
 * Container-owned base config for the peer-mode CODEX_HOME. PARALLEL
 * IMPLEMENTATION of `buildContainerCodexConfig()` in src/providers/codex.ts
 * (host and container share no modules by design — keep the two in sync).
 * [features] is load-bearing: hooks = the destructive-action guard chain,
 * multi_agent = native subagents, memories/goals = their MCP surfaces.
 */
const CONTAINER_CODEX_CONFIG_BASE = [
  '# Generated by NanoClaw (codex-companion-setup.ts) — container-owned.',
  '# Rewritten on every spawn; MCP blocks below come from container wiring.',
  'sandbox_mode = "workspace-write"',
  'approval_policy = "on-request"',
  'approvals_reviewer = "auto_review"',
  'model_context_window = 400000',
  'model_auto_compact_token_limit = 360000',
  '',
  '[features]',
  'context_management = true',
  'hooks = true',
  'fast_mode = false',
  'memories = true',
  'goals = true',
  'multi_agent = true',
  '',
  '[agents]',
  // No `default_subagent_reasoning_effort` — deliberately the same as
  // src/providers/codex.ts and the host's own config (operator, 2026-09-17):
  // a Codex subagent runs at Codex's native default unless its spawn or its
  // role names an effort.
  //
  // A plain literal, not a template: src/provider-surfaces.test.ts evaluates
  // THIS array literal in a bare `new Function` scope to compare it against the
  // host's, so the literal may reference only bindings that test supplies.
  'max_concurrent_threads_per_session = 5',
  '',
  ...['/workspace/agent', '/workspace/workgroup', '/workspace/worktrees', '/tmp'].flatMap((proj) => [
    `[projects."${proj}"]`,
    'trust_level = "trusted"',
    '',
  ]),
].join('\n');

/** Group-owned named-role roster, mounted with the group folder. */
const GROUP_CODEX_AGENTS_DIR = '/workspace/agent/.codex/agents';

function log(msg: string): void {
  console.error(`[codex-companion-setup] ${msg}`);
}

export function renderMcpServerForTest(name: string, config: McpServerConfig): string[] {
  return renderMcpServer(name, config);
}

export function buildRuntimeConfigForTest(mcpServers: Record<string, McpServerConfig>): string {
  return buildRuntimeConfig(mcpServers);
}

export function stripPluginsAndMarketplacesForTest(toml: string): string {
  return stripPluginsAndMarketplaces(toml);
}

function renderMcpServer(name: string, config: McpServerConfig): string[] {
  // The same renderer as writeCodexMcpConfigToml: one malformed entry makes
  // codex reject the file and drops every MCP server.
  if (config.type === 'sse') {
    throw new Error(`MCP server "${name}" uses deprecated SSE transport. Use type: "http" instead.`);
  }
  return renderCodexMcpServer(name, config);
}

function parseTomlString(raw: string): string {
  const m = raw.match(/^"((?:[^"\\]|\\.)*)"/);
  if (!m) return raw;
  return m[1].replace(/\\"/g, '"').replace(/\\\\/g, '\\');
}

function parseTomlInlineStringMap(raw: string): Record<string, string> {
  const map: Record<string, string> = {};
  const body = raw
    .trim()
    .replace(/^\{\s*/, '')
    .replace(/\s*\}$/, '');
  for (const part of splitTomlArray(body)) {
    const m = part.match(/^("((?:[^"\\]|\\.)*)"|[A-Za-z_][A-Za-z0-9_-]*)\s*=\s*(.+)$/);
    if (!m) continue;
    const key = m[2] !== undefined ? parseTomlString(m[1]) : m[1];
    map[key] = parseTomlString(m[3].trim());
  }
  return map;
}

function splitTomlArray(inside: string): string[] {
  const parts: string[] = [];
  let depth = 0;
  let buf = '';
  let inString = false;
  let escape = false;
  for (const ch of inside) {
    if (escape) {
      buf += ch;
      escape = false;
      continue;
    }
    if (ch === '\\') {
      buf += ch;
      escape = true;
      continue;
    }
    if (ch === '"') {
      inString = !inString;
      buf += ch;
      continue;
    }
    if (!inString) {
      if (ch === '[') depth++;
      if (ch === ']') depth--;
      if (ch === ',' && depth === 0) {
        parts.push(buf.trim());
        buf = '';
        continue;
      }
    }
    buf += ch;
  }
  if (buf.trim()) parts.push(buf.trim());
  return parts;
}

/**
 * Build the runtime config.toml: the generated container base plus exactly
 * the MCP servers the agent-runner wired for this session. The host's
 * config.toml contributes NOTHING — not settings, not MCP servers. (The old
 * host-union behavior leaked host-personal state — model pin, personality,
 * the projects trust table, hook/TUI state — into every peer session.)
 */
function buildRuntimeConfig(mcpServers: Record<string, McpServerConfig>): string {
  const mcpLines: string[] = [];
  for (const [name, config] of Object.entries(mcpServers)) {
    if (name.toLowerCase() === 'gitnexus') continue; // container-retired
    mcpLines.push(...renderMcpServer(name, config));
    mcpLines.push('');
  }
  return [CONTAINER_CODEX_CONFIG_BASE, '', '# --- nanoclaw runtime MCP servers ---', '', ...mcpLines].join('\n');
}

/**
 * Strip every `[plugins.*]` and `[marketplaces.*]` table from the host
 * config. Containers must have ZERO dependency on host CLI plugin state —
 * rather than rewrite the host's marketplace `source =` paths to point into
 * the container (the old approach), we drop these tables entirely and
 * register plugins fresh from `/workspace/plugins` via
 * `registerContainerCodexPlugins`.
 *
 * Matches both bare (`[marketplaces.foo]`) and quoted-segment
 * (`[plugins."foo@bar"]`) dotted table headers, plus the bare table name on
 * its own (`[plugins]`). Same line-scanning shape as other table
 * scanners in this file — a real TOML table ends at the next
 * `[...]` header, matching or not.
 */
function isPluginTable(tableName: string): boolean {
  return (
    tableName === 'plugins' ||
    tableName === 'marketplaces' ||
    tableName === 'plugin_marketplaces' ||
    tableName.startsWith('plugins.') ||
    tableName.startsWith('marketplaces.') ||
    tableName.startsWith('plugin_marketplaces.')
  );
}

function splitPluginsAndMarketplaces(toml: string): { base: string; plugins: string } {
  const base: string[] = [];
  const plugins: string[] = [];
  let inStrippedBlock = false;
  for (const line of toml.split('\n')) {
    const header = parseTomlTableHeader(line);
    if (header !== null) {
      inStrippedBlock = isPluginTable(header);
    }
    (inStrippedBlock ? plugins : base).push(line);
  }
  return { base: base.join('\n'), plugins: plugins.join('\n') };
}

function stripPluginsAndMarketplaces(toml: string): string {
  return splitPluginsAndMarketplaces(toml).base;
}

function projectCodexPluginConfig(primaryToml: string, targetToml: string): string {
  const primaryPlugins = splitPluginsAndMarketplaces(primaryToml).plugins.trim();
  const targetBase = stripPluginsAndMarketplaces(targetToml).trimEnd();
  return [targetBase, primaryPlugins].filter(Boolean).join('\n\n') + '\n';
}

export function projectCodexPluginConfigForTest(primaryToml: string, targetToml: string): string {
  return projectCodexPluginConfig(primaryToml, targetToml);
}

/**
 * Fail closed on CODEX, not on the CONTAINER.
 *
 * Returning `null` here would be a guard BYPASS, not a graceful degrade: the
 * caller only sets `CODEX_HOME` on a non-null return, so a peer-mode
 * `codex exec` would fall back to `/home/node/.codex` — the staged home, which
 * HAS auth and never receives the in-tree PreToolUse destructive-action guard
 * chain. Net: an authenticated, working, UNGUARDED codex. Writing the guard
 * into that directory instead is not an option: the host regenerates its
 * `config.toml` on every spawn, so the entries would not survive a respawn.
 *
 * So we hand back a nonexistent sentinel. Codex refuses to start on it and
 * cannot reach the staged auth or config, while the primary provider
 * (Claude/OpenCode) boots and works normally — these are all filesystem
 * failures in the container's writable home, and under disk pressure throwing
 * would convert "peer codex degraded" into "every container crash-loops".
 * It also needs no filesystem operation, so it still holds in the case where
 * `mkdirSync` itself is what failed.
 */
function failClosed(what: string, err: unknown): string {
  const detail = err instanceof Error ? err.message : String(err);
  log(
    `FAIL-CLOSED: peer-mode Codex DISABLED for this container — ${what}: ${detail}. ` +
      `CODEX_HOME is set to the nonexistent sentinel ${FAILED_CODEX_HOME}, so \`codex exec\` will refuse ` +
      `to start rather than run unguarded against the staged ${HOST_CODEX_DIR}. ` +
      `The primary agent provider is unaffected. Most likely cause: no space / bad permissions on /home/node.`,
  );
  return FAILED_CODEX_HOME;
}

/**
 * Trust entries for every plugin hook mounted at `/workspace/plugins`.
 *
 * DECISION: NanoClaw trusts operator-curated plugin hooks under Codex. The
 * mount is read-only and operator-curated, and the Claude provider already
 * dispatches these same plugins' hooks unconditionally through the SDK hook
 * pass-through (`providers/claude.ts`), so declining to trust them under Codex
 * buys no isolation — it only makes the two providers behave differently. The
 * observable effect today is that the workflow-agents Codex destructive guard
 * and its SessionStart role installer are silently inert in Codex containers.
 *
 * Keyed off `planCodexPluginRegistration`, so a plugin excluded from
 * registration (deny-sibling, no manifest) is never trusted.
 */
function pluginHookTrustEntries(pluginsRoot: string): CodexHookTrustEntry[] {
  if (!fs.existsSync(pluginsRoot)) return [];
  const entries: CodexHookTrustEntry[] = [];
  for (const plan of planCodexPluginRegistration(pluginsRoot)) {
    if (plan.action !== 'register' || !plan.pluginDir || !plan.entryName || !plan.marketplaceName) continue;
    entries.push(
      ...collectPluginHookTrustEntries({
        pluginId: `${plan.entryName}@${plan.marketplaceName}`,
        dir: plan.pluginDir,
      }),
    );
  }
  return entries;
}

/**
 * Trust entries for the hooks.json NanoClaw GENERATES into `codexHome` — the
 * PreToolUse/PostToolUse destructive-action guard chain, and nothing else.
 *
 * Shared by the writer (`syncCodexHookTrust`) and the runtime verifier
 * (`verifyCodexHookTrust`) so the check cannot drift from the write and quietly
 * assert a different key set than the one that was written.
 */
function generatedHookTrustEntries(codexHome: string, opts?: { emailGateTimeoutSec?: number }): CodexHookTrustEntry[] {
  return collectCodexHookTrustEntries(path.join(codexHome, 'hooks.json'), buildCodexHooksJson(opts).hooks);
}

/**
 * Assert against the RUNNING app-server that every generated guard handler will
 * actually be dispatched. Throws — a refused spawn — when any will not.
 *
 * Call after `initializeCodexAppServer` on the same connection. Cost measured on
 * codex 0.154.0 against a scratch CODEX_HOME: 11 ms for the first `hooks/list`,
 * 2 ms after, so this runs on EVERY app-server spawn rather than once a session.
 *
 * **Deliberately fatal, including when the RPC itself fails.** The failure this
 * exists to catch is silent by construction: a handler whose hash does not match
 * reports `untrusted` and is simply never dispatched, while the session runs
 * normally. A version drift that removes or renames `hooks/list` is the same
 * class of event as one that changes the hashed field set, so degrading to a
 * warning here would restore exactly the silence the check is for. A Codex
 * container that cannot prove its guard chain live does not start.
 *
 * Scoped to the generated handlers. A mounted plugin's hook reading back
 * undispatchable is LOGGED, not fatal: one oddly-shaped third-party plugin must
 * not take the container down, and the guard core does not depend on any plugin
 * being mounted.
 */
export async function verifyCodexHookTrust(
  server: AppServer,
  codexHome: string,
  opts?: { emailGateTimeoutSec?: number },
): Promise<void> {
  const expected = generatedHookTrustEntries(codexHome, opts).map((entry) => entry.key);
  if (expected.length === 0) {
    // buildCodexHooksJson always emits both events, so an empty set means the
    // collector stopped recognizing its own output — fail closed rather than
    // vacuously pass.
    throw new Error(
      `Codex hook trust verification: derived NO expected handler keys for ${codexHome} — ` +
        `refusing to spawn an app-server whose guard chain cannot be checked.`,
    );
  }

  let listed;
  try {
    listed = await listCodexHooks(server);
  } catch (err) {
    const detail = err instanceof Error ? err.message : String(err);
    log(
      `FAIL-CLOSED: could not read hooks/list from the app-server — the destructive-action guard chain ` +
        `cannot be proven live, so the spawn is refused: ${detail}`,
    );
    throw new Error(`Codex hook trust verification failed (hooks/list unavailable): ${detail}`);
  }

  const verdict = classifyCodexHookList(listed.entries, expected);
  for (const problem of verdict.plugin) {
    log(`Non-generated hook will NOT fire (reported, not fatal): ${formatCodexHookTrustProblem(problem)}`);
  }
  for (const warning of listed.warnings) log(`hooks/list warning: ${warning}`);
  for (const error of listed.errors) log(`hooks/list error: ${error}`);

  if (verdict.generated.length > 0) {
    const detail = verdict.generated.map(formatCodexHookTrustProblem).join('; ');
    log(
      `FAIL-CLOSED: ${verdict.generated.length} of ${expected.length} generated guard handler(s) in ${codexHome} ` +
        `would NEVER be dispatched by this codex — ${detail}. ` +
        `Refusing the spawn: a Codex session with an inert destructive-action guard is the exact silent ` +
        `state this check exists to make unreachable.`,
    );
    throw new Error(`Codex hook trust verification failed for ${codexHome}: ${detail}`);
  }

  log(
    `Hook trust verified live: ${verdict.generatedOk.length} generated guard handler(s) dispatchable in ${codexHome}`,
  );
}

/**
 * Rewrite the `[hooks.state.*]` tables in `<codexHome>/config.toml` so every
 * hook this container generates or mounts is TRUSTED.
 *
 * Without this, Codex ≥0.154 loads the hooks, reports them as `untrusted` via
 * `hooks/list`, and never dispatches them — the destructive-action guard chain
 * fails open and silent. See `providers/codex-hook-trust.ts` for the hash.
 *
 * Idempotent and keyed on the home passed in, so it is safe to call again
 * after `codex plugin add` has rewritten config.toml and after an OAuth
 * fallback rotation has moved CODEX_HOME.
 *
 * `pluginsRoot` defaults to the real `/workspace/plugins` mount; it is
 * injectable so tests can drive a fixture tree without a container.
 */
export function syncCodexHookTrust(
  codexHome: string,
  opts?: { emailGateTimeoutSec?: number; pluginsRoot?: string },
): void {
  const configPath = path.join(codexHome, 'config.toml');
  const entries = [
    ...generatedHookTrustEntries(codexHome, opts),
    ...pluginHookTrustEntries(opts?.pluginsRoot ?? CONTAINER_PLUGINS_DIR),
  ];
  try {
    fs.mkdirSync(codexHome, { recursive: true });
    // Asserting variant: the trust rows are the one table in this file that
    // nothing else can restore, so the post-write check reads the COMMITTED
    // bytes back and refuses if a row this call meant to write is not in them.
    // Checking what was rendered instead would only prove the renderer agrees
    // with itself — the same criticism `docs/review-notes/817.md` records.
    writeCodexConfigTomlAsserting(
      configPath,
      (existing) => mergeCodexHookTrustIntoToml(existing, entries),
      codexHookTrustTables(entries),
    );
  } catch (err) {
    // THROWS, deliberately. Swallowing here leaves hooks.json on disk with no
    // matching trust entry — precisely the state this module exists to
    // eliminate: codex loads the handlers, reports them untrusted, never
    // dispatches them, and the app-server starts anyway, so the
    // destructive-action guard is present, inert and silent. Returning normally
    // would also let `writeCodexHooksAndTrust` report a postcondition it did
    // not achieve, and every caller below it continues straight into a spawn.
    // Each caller decides what to do with the failure; none of them may decide
    // it by default.
    const detail = err instanceof Error ? err.message : String(err);
    log(`FAILED to write hook trust to ${configPath} — Codex hooks would be UNTRUSTED and never fire: ${detail}`);
    throw new Error(`could not write Codex hook trust entries to ${configPath}: ${detail}`);
  }
  log(`Hook trust: ${entries.length} entry(ies) written to ${configPath}`);
}

/**
 * Write `hooks.json` AND the trust entries that make Codex actually run it.
 * Every caller that used to call `writeCodexHooksJson` directly must call this
 * instead — a hooks.json with no matching trust entry is a no-op file.
 */
export function writeCodexHooksAndTrust(opts?: {
  emailGateTimeoutSec?: number;
  codexHome?: string;
  pluginsRoot?: string;
}): string {
  const home = writeCodexHooksJson(opts);
  syncCodexHookTrust(home, opts);
  return home;
}

/**
 * Set up `/home/node/.codex-runtime/` and return the path so callers can
 * point `CODEX_HOME` at it. Returns `null` ONLY when the codex auth mount is
 * absent (no host `~/.codex/auth.json`) — benign, since codex cannot run at
 * all without auth. Every other failure returns the nonexistent
 * `FAILED_CODEX_HOME` sentinel, which disables peer-mode codex without taking
 * the container down (see `failClosed`). No filesystem failure throws.
 * (`buildRuntimeConfig` can still throw on a malformed MCP server entry — a
 * wiring bug, not a runtime condition, and pre-existing behavior.)
 *
 * `runtime` identifies the host agent runtime driving this peer-mode Codex
 * invocation (never `'codex'` itself — a codex-primary session writes its
 * own CODEX_HOME directly and never calls this function). Defaults to
 * `'claude'` for back-compat with callers that don't pass it.
 */
export function setupCodexRuntime(
  mcpServers: Record<string, McpServerConfig>,
  runtime: AgentRuntime = 'claude',
): string | null {
  const hostAuth = path.join(HOST_CODEX_DIR, 'auth.json');
  if (!fs.existsSync(hostAuth)) {
    log('Host codex auth not mounted — skipping CODEX_HOME runtime setup');
    return null;
  }

  try {
    fs.mkdirSync(RUNTIME_CODEX_DIR, { recursive: true });
  } catch (err) {
    return failClosed('could not create the runtime dir', err);
  }

  // Symlink auth.json so OAuth token refresh writes back to the host's
  // mounted file. Replace any stale link from a previous run.
  const runtimeAuth = path.join(RUNTIME_CODEX_DIR, 'auth.json');
  try {
    if (fs.existsSync(runtimeAuth) || fs.lstatSync(runtimeAuth, { throwIfNoEntry: false } as never)) {
      fs.unlinkSync(runtimeAuth);
    }
  } catch {
    /* not present — fine */
  }
  try {
    fs.symlinkSync(hostAuth, runtimeAuth);
  } catch (err) {
    return failClosed('could not symlink auth.json', err);
  }

  // agents/: symlink the GROUP-OWNED subagent roster
  // (groups/<folder>/.codex/agents, mounted at /workspace/agent/.codex/agents,
  // populated by src/codex-sync.ts) so codex-as-peer sees the same named
  // roles Codex primary sees. Deliberately never the host's ~/.codex/agents —
  // host CLI config must not shape a container agent.
  const groupAgentsDir = GROUP_CODEX_AGENTS_DIR;
  const runtimeAgentsDir = path.join(RUNTIME_CODEX_DIR, 'agents');
  if (fs.existsSync(groupAgentsDir)) {
    try {
      try {
        fs.unlinkSync(runtimeAgentsDir);
      } catch {
        /* fresh */
      }
      fs.symlinkSync(groupAgentsDir, runtimeAgentsDir);
    } catch (err) {
      log(`Failed to symlink agents/: ${err instanceof Error ? err.message : String(err)}`);
    }
  }

  // NOTE: no `plugins/` cache symlink and no `.tmp/marketplaces/` snapshot
  // symlink here (deliberately removed). Both existed only to make sense of
  // host-inherited `[plugins.*]` / `[marketplaces.*]` config blocks — now
  // that `buildRuntimeConfig` never carries host config at all (see
  // `stripPluginsAndMarketplaces`), nothing in the runtime config.toml
  // references either path, and every plugin is registered fresh below via
  // `registerContainerCodexPlugins`. Containers must have zero dependency on
  // host CLI plugin state.

  const runtimeConfigPath = path.join(RUNTIME_CODEX_DIR, 'config.toml');
  try {
    // Full regeneration: the peer-mode runtime config carries NOTHING from
    // whatever was here before (see `buildRuntimeConfig`), so `readBase: false`
    // — an unreadable previous file is no reason to disable peer Codex when
    // none of it was going to be carried forward. Still committed through the
    // shared primitive, so an ENOSPC mid-write leaves the last valid runtime
    // config standing rather than a truncated one that the next
    // `codex plugin add` would decorate and the spawn would believe.
    writeCodexConfigToml(runtimeConfigPath, () => buildRuntimeConfig(mcpServers), { readBase: false });
  } catch (err) {
    return failClosed('could not write the merged config.toml', err);
  }

  // Peer-mode `codex exec` reads this synthesized CODEX_HOME directly. Its
  // commands do not pass back through the parent Claude/OpenCode Bash hook, so
  // install the same in-tree PreToolUse chain used by the Codex provider before
  // exposing the runtime. Fail closed if the guard wiring cannot be persisted.
  try {
    writeCodexHooksAndTrust({ codexHome: RUNTIME_CODEX_DIR });
  } catch (err) {
    return failClosed('could not write the peer Codex hooks.json', err);
  }

  // Container-owned plugin registration: build the runtime's own plugin
  // cache from /workspace/plugins rather than inheriting the host's. Must
  // run AFTER config.toml is written (registration mutates config.toml
  // in-place via `codex plugin` under CODEX_HOME=RUNTIME_CODEX_DIR).
  registerContainerCodexPlugins(RUNTIME_CODEX_DIR, runtime);

  // Re-sync AFTER registration: `codex plugin add` rewrites config.toml in
  // place, and the newly-registered plugins' own hook files only become
  // reachable once they are registered. Idempotent, so re-running it costs a
  // file rewrite and nothing else. Fails closed for the same reason the write
  // above does — `codex plugin add` has already rewritten config.toml by this
  // point, so a failure here does not leave the pre-registration entries
  // standing, it leaves none.
  try {
    syncCodexHookTrust(RUNTIME_CODEX_DIR);
  } catch (err) {
    return failClosed('could not re-write the peer Codex hook trust after plugin registration', err);
  }

  // Skills mirror is already populated by index.ts at startup with the correct
  // runtime; calling it again here without a runtime arg would default to
  // 'codex' and strip workflow-agents skills for opencode containers that have
  // codex auth mounted (codex-as-peer mode). Idempotency of syncSkillSymlinks
  // makes the call cheap, but the wrong denylist makes it incorrect.

  log(`CODEX_HOME runtime ready at ${RUNTIME_CODEX_DIR} (${Object.keys(mcpServers).length} MCP servers merged)`);
  return RUNTIME_CODEX_DIR;
}

function replaceWithDirectorySymlink(linkPath: string, targetPath: string): void {
  fs.rmSync(linkPath, { recursive: true, force: true });
  if (!fs.existsSync(targetPath)) return;
  fs.mkdirSync(path.dirname(linkPath), { recursive: true });
  fs.symlinkSync(targetPath, linkPath, 'dir');
}

/**
 * Register plugins for a Codex-primary session into its session-local
 * `/home/node/.codex` and project that one registration into any OAuth
 * fallback homes. Fallback homes share the derived cache through symlinks;
 * auth and rollout state remain independent.
 */
export function setupCodexPrimaryRuntime(
  fallbackHomes: string[] = (process.env.CODEX_FALLBACK_HOMES ?? '')
    .split(':')
    .map((home) => home.trim())
    .filter(Boolean),
): { registered: string[]; skipped: string[]; errors: string[]; projectedFallbacks: string[] } {
  const registration = registerContainerCodexPlugins(HOST_CODEX_DIR, 'codex');
  // Trust the freshly-registered plugin hooks (and the generated guard chain)
  // in the primary home. The provider rewrites config.toml + hooks.json again
  // right before each app-server spawn (providers/codex.ts), but that rewrite
  // preserves nothing it did not author, so the entries must be re-derived
  // there too — `writeCodexHooksAndTrust` is what both paths go through.
  //
  // Recorded rather than thrown, and ONLY here: this runs at startup, and the
  // invariant that matters — no app-server without a trusted guard chain — is
  // enforced at the spawn, where `writeCodexHooksAndTrust` now propagates. So a
  // transient failure at startup costs a loud error and the next spawn's
  // refusal, not a crash-loop that takes the container down for a condition the
  // spawn would have caught anyway. It is never silent.
  try {
    syncCodexHookTrust(HOST_CODEX_DIR);
  } catch (err) {
    registration.errors.push(
      `${HOST_CODEX_DIR}: hook trust sync failed — ${err instanceof Error ? err.message : String(err)}`,
    );
  }
  const projectedFallbacks: string[] = [];
  const primaryConfigPath = path.join(HOST_CODEX_DIR, 'config.toml');
  // Same class as the read inside `syncCodexHookTrust`, at the site that feeds
  // EVERY fallback home: `existsSync` answers false on EACCES as readily as on
  // absence, so an unreadable primary used to project an EMPTY config into each
  // fallback — dropping `[features] hooks = true` and the plugin tables there,
  // in one pass, for the homes an OAuth rotation is about to switch to. Skip the
  // projection instead: leaving a fallback's own config standing is recoverable,
  // overwriting it with nothing is not, and the spawn re-derives hooks and trust
  // for whichever home it lands on.
  const primaryConfig = ((): string | null => {
    try {
      return readCodexConfigToml(primaryConfigPath);
    } catch (err) {
      registration.errors.push(
        `${primaryConfigPath}: unreadable — skipped projecting it into ${fallbackHomes.length} fallback home(s) ` +
          `rather than writing an empty config over them: ${err instanceof Error ? err.message : String(err)}`,
      );
      return null;
    }
  })();

  // Pairing each home with the base it projects is what lets the "we could not
  // read the primary" case be an EMPTY list rather than a null threaded through
  // the loop body.
  const projections = primaryConfig === null ? [] : fallbackHomes.map((home) => [home, primaryConfig] as const);

  for (const [fallbackHome, basePrimaryConfig] of projections) {
    try {
      fs.mkdirSync(fallbackHome, { recursive: true });
      replaceWithDirectorySymlink(path.join(fallbackHome, 'plugins'), path.join(HOST_CODEX_DIR, 'plugins'));
      replaceWithDirectorySymlink(
        path.join(fallbackHome, '.tmp', 'marketplaces'),
        path.join(HOST_CODEX_DIR, '.tmp', 'marketplaces'),
      );

      const fallbackConfigPath = path.join(fallbackHome, 'config.toml');
      writeCodexConfigToml(fallbackConfigPath, (fallbackConfig) =>
        projectCodexPluginConfig(basePrimaryConfig, fallbackConfig),
      );
      // Trust entries are keyed on the home's OWN hooks.json path, so the
      // projection cannot carry the primary's — derive them for this home.
      syncCodexHookTrust(fallbackHome);
      projectedFallbacks.push(fallbackHome);
    } catch (err) {
      registration.errors.push(
        `${fallbackHome}: fallback projection failed — ${err instanceof Error ? err.message : String(err)}`,
      );
    }
  }

  log(
    `Codex-primary plugin runtime: ${registration.registered.length} registered, ` +
      `${projectedFallbacks.length} fallback(s) projected, ${registration.errors.length} errors`,
  );
  return { ...registration, projectedFallbacks };
}

function isDirectorySafe(p: string): boolean {
  try {
    return fs.statSync(p).isDirectory();
  } catch {
    return false;
  }
}

/**
 * Read the registerable ENTRY NAME for a plugin dir from its
 * `.codex-plugin/plugin.json` `name` field — NOT the folder name. A plugin
 * repo's folder name doesn't always match its Codex plugin name (e.g. the
 * Wix skills repo ships at `~/plugins/skills` but its plugin.json name is
 * `wix`; using the folder name for `codex plugin add` would hard-error with
 * "plugin.json name `wix` does not match marketplace plugin name `skills`").
 * Returns `null` when the manifest is absent/unreadable/malformed — the
 * caller treats that as "not a registerable Codex plugin", not an error.
 */
function readCodexPluginEntryName(pluginDir: string): string | null {
  try {
    const raw = fs.readFileSync(path.join(pluginDir, '.codex-plugin', 'plugin.json'), 'utf-8');
    const parsed = JSON.parse(raw) as { name?: unknown };
    return typeof parsed.name === 'string' && parsed.name.trim() ? parsed.name : null;
  } catch {
    return null;
  }
}

/**
 * Read the MARKETPLACE NAME for a plugin dir from its
 * `.agents/plugins/marketplace.json` `name` field — this is the name
 * `codex plugin marketplace add <dir>` registers the marketplace under, and
 * the `@marketplace` half of the `codex plugin add <entry>@<marketplace>`
 * argument. Returns `null` when the manifest is missing — plugins without it
 * aren't natively Codex-registerable.
 */
function readCodexMarketplaceName(pluginDir: string): string | null {
  // `.agents/plugins/` is the Codex-native location; Codex also accepts a
  // `.claude-plugin/marketplace.json` (verified: `codex plugin marketplace add`
  // resolves anthropics/knowledge-work-plugins through it), which is what
  // Claude-first marketplace monorepos ship.
  for (const rel of [
    path.join('.agents', 'plugins', 'marketplace.json'),
    path.join('.claude-plugin', 'marketplace.json'),
  ]) {
    try {
      const parsed = JSON.parse(fs.readFileSync(path.join(pluginDir, rel), 'utf-8')) as { name?: unknown };
      if (typeof parsed.name === 'string' && parsed.name.trim()) return parsed.name;
    } catch {
      /* try the next location */
    }
  }
  return null;
}

/**
 * Sub-plugin dirs inside a marketplace MONOREPO that are themselves registerable.
 *
 * Some repos carry no top-level `.codex-plugin/plugin.json` — the manifests live one
 * level down (`role-specific-plugins/plugins/data-analytics/`,
 * `claude-plugins-official/plugins/playground/`, `knowledge-work-plugins/data/`).
 * Registering only top-level manifests silently drops those entire repos, which is
 * exactly how data-analytics stopped reaching Codex containers.
 *
 * We only return sub-dirs that BOTH exist on disk AND carry a `.codex-plugin` manifest.
 * That is what makes a sparse checkout do the right thing: a monorepo's marketplace.json
 * may advertise a dozen plugins, but if only one was checked out, only that one registers.
 */
function findCodexSubPlugins(
  pluginDir: string,
  repoName: string,
  excluded: ExcludedPlugins,
): Array<{ dir: string; entryName: string }> {
  const found: Array<{ dir: string; entryName: string }> = [];
  const seen = new Set<string>();
  // Both monorepo layouts: `<root>/plugins/<sub>` and `<root>/<sub>`.
  for (const container of [path.join(pluginDir, 'plugins'), pluginDir]) {
    if (!isDirectorySafe(container)) continue;
    // The relative path of THIS layout's container, as the plugins root sees
    // it. Built from the repo's own entry name, not from `pluginDir` — the
    // exclusion is asked about the walk's own path, never a resolved one.
    const containerRel = container === pluginDir ? repoName : `${repoName}/plugins`;
    let subs: string[] = [];
    try {
      subs = fs.readdirSync(container);
    } catch {
      continue;
    }
    for (const sub of subs) {
      if (sub.startsWith('.')) continue;
      const dir = path.join(container, sub);
      if (isExcludedPluginPath(`${containerRel}/${sub}`, excluded)) continue;
      if (seen.has(dir) || !isDirectorySafe(dir)) continue;
      const entryName = readCodexPluginEntryName(dir);
      if (!entryName) continue;
      seen.add(dir);
      found.push({ dir, entryName });
    }
  }
  return found;
}

export interface CodexPluginRegistrationPlan {
  /** Display label. For a monorepo sub-plugin this is `<repo>/<entry>`. */
  name: string;
  action: 'register' | 'skip';
  reason?: string;
  entryName?: string;
  marketplaceName?: string;
  /**
   * Top-level folder under the plugins root that `codex plugin marketplace add`
   * must target. Distinct from `name`: a monorepo sub-plugin's marketplace is the
   * REPO root, not the sub-directory, so the dir can't be derived from the label.
   */
  repoName?: string;
  /**
   * Absolute dir holding this plugin's `.codex-plugin/plugin.json`. For a
   * single-plugin repo that is the repo root; for a monorepo sub-plugin it is
   * the SUB-directory, which is neither `repoName` nor derivable from `name`
   * (the folder name and the manifest's entry name need not match — see
   * `readCodexPluginEntryName`). `syncCodexHookTrust` needs it to read the
   * plugin's declared hooks file.
   */
  pluginDir?: string;
}

/**
 * Pure planning pass over a plugins root: decides register-vs-skip for each
 * top-level entry without spawning `codex` and without any writes. Kept
 * separate from `registerContainerCodexPlugins` so the decision logic
 * (deny-sibling routing, manifest presence, name resolution) is unit-testable
 * against a fake plugins root with no subprocess involved.
 *
 * A per-group `excludePlugins` TOP-LEVEL entry, and the in-tree-shadowed
 * plugins, need no handling here — `container-runner.ts` omits those from the
 * `/workspace/plugins` mount before the container ever starts, so they simply
 * never appear as entries in `pluginsRoot`. The top-level `excludePlugins`
 * check below is belt-and-braces, and cheap: one Set lookup.
 *
 * A SUB-PLUGIN path entry IS handled here, because the host mounts the repo
 * whole and only this walker knows which sub-plugins it would have registered.
 * An excluded sub-plugin is never `codex plugin add`ed — and so, since
 * `pluginHookTrustEntries` keys off this plan, never gains a hook trust entry
 * either. There is no host-side mask because the host cannot predict what
 * this walker will see; the list is honoured in the walker's own namespace
 * instead (`plugin-exclusions.ts`).
 */
export function planCodexPluginRegistration(
  pluginsRoot: string,
  excluded: ExcludedPlugins = loadExcludedPlugins(),
): CodexPluginRegistrationPlan[] {
  let entries: string[] = [];
  try {
    entries = fs.readdirSync(pluginsRoot);
  } catch {
    return [];
  }

  const plans: CodexPluginRegistrationPlan[] = [];
  for (const name of entries) {
    const dir = path.join(pluginsRoot, name);
    if (isExcludedPluginPath(name, excluded)) {
      plans.push({ name, action: 'skip', reason: 'excluded-by-config' });
      continue;
    }
    if (!isDirectorySafe(dir)) {
      plans.push({ name, action: 'skip', reason: 'not-a-directory' });
      continue;
    }
    if (readPluginDenySiblings(dir).has('codex')) {
      plans.push({ name, action: 'skip', reason: 'denied-for-codex' });
      continue;
    }
    const marketplaceName = readCodexMarketplaceName(dir);
    if (!marketplaceName) {
      plans.push({ name, action: 'skip', reason: 'no-marketplace-manifest' });
      continue;
    }
    const entryName = readCodexPluginEntryName(dir);
    if (entryName) {
      // Single-plugin repo: the repo root IS the plugin.
      plans.push({ name, action: 'register', entryName, marketplaceName, repoName: name, pluginDir: dir });
      continue;
    }
    // Marketplace monorepo: no manifest at the root, so register each checked-out
    // sub-plugin against the repo's marketplace. `codex plugin marketplace add` is
    // run once per plan against the same repo dir, which is idempotent.
    const subs = findCodexSubPlugins(dir, name, excluded);
    if (subs.length === 0) {
      plans.push({ name, action: 'skip', reason: 'no-codex-plugin-manifest' });
      continue;
    }
    for (const sub of subs) {
      plans.push({
        name: `${name}/${sub.entryName}`,
        action: 'register',
        entryName: sub.entryName,
        marketplaceName,
        repoName: name,
        pluginDir: sub.dir,
      });
    }
  }
  return plans;
}

function describeSpawnFailure(result: SpawnSyncReturns<string>): string {
  if (result.error) return result.error.message;
  const stderr = (result.stderr ?? '').toString().trim();
  return stderr || `exit code ${result.status ?? 'unknown'}`;
}

/**
 * Register every registerable plugin under `/workspace/plugins` into the
 * runtime CODEX_HOME's OWN plugin cache. This is the container-owned
 * replacement for the old host-plugins-cache symlink: instead of borrowing
 * whatever `~/.codex/plugins/cache` the host happens to have, the container
 * runs `codex plugin marketplace add <dir>` then
 * `codex plugin add <entryName>@<marketplaceName>` for each plugin, both
 * with `CODEX_HOME` pointed at the runtime dir — materializing a
 * container-local cache under `<runtimeHome>/plugins/cache/...`.
 *
 * A single bad plugin must not break container startup: every `spawnSync`
 * failure is captured into `errors` and the loop continues, never throws.
 */
export function registerContainerCodexPlugins(
  runtimeHome: string,
  runtime: AgentRuntime,
): { registered: string[]; skipped: string[]; errors: string[] } {
  const registered: string[] = [];
  const skipped: string[] = [];
  const errors: string[] = [];

  // Cheap no-op when no plugins are mounted at all (e.g. operator has no
  // ~/plugins tree, or every entry was excluded before the mount).
  if (!fs.existsSync(CONTAINER_PLUGINS_DIR)) {
    return { registered, skipped, errors };
  }

  const plans = planCodexPluginRegistration(CONTAINER_PLUGINS_DIR);
  const env = { ...process.env, CODEX_HOME: runtimeHome };

  for (const plan of plans) {
    if (plan.action === 'skip') {
      skipped.push(plan.name);
      continue;
    }

    // Monorepo sub-plugins register against their REPO root, not the label path.
    const dir = path.join(CONTAINER_PLUGINS_DIR, plan.repoName ?? plan.name);
    const addMarketplace = spawnSync('codex', ['plugin', 'marketplace', 'add', dir], {
      env,
      timeout: 60_000,
      encoding: 'utf-8',
    });
    if (addMarketplace.status !== 0) {
      errors.push(`${plan.name}: marketplace add failed — ${describeSpawnFailure(addMarketplace)}`);
      continue;
    }

    const addPlugin = spawnSync('codex', ['plugin', 'add', `${plan.entryName}@${plan.marketplaceName}`], {
      env,
      timeout: 60_000,
      encoding: 'utf-8',
    });
    if (addPlugin.status !== 0) {
      errors.push(`${plan.name}: plugin add failed — ${describeSpawnFailure(addPlugin)}`);
      continue;
    }

    registered.push(plan.name);
  }

  log(
    `Container Codex plugin registration (runtime=${runtime}): ` +
      `${registered.length} registered, ${skipped.length} skipped, ${errors.length} errors` +
      (errors.length > 0 ? ` — ${errors.join('; ')}` : ''),
  );

  return { registered, skipped, errors };
}

/**
 * Populate `/home/node/.agents/skills/` with symlinks to every discoverable
 * skill — container-bundled NanoClaw skills + host plugin tree. Codex
 * auto-scans this dir (verified via `codex debug prompt-input`; appears as
 * discovery root `r1`), so this is what makes plugin skills like
 * `humanizer`, `impeccable`, etc. visible to Codex sessions.
 *
 * Called unconditionally from agent-runner startup — needed for BOTH
 * codex-primary (helper-codex) and codex-as-peer (helper running the codex
 * companion script). Idempotent: `syncDiscoveredSkillSymlinks` reconciles
 * existing entries (creates/removes/leaves as appropriate).
 */
export function syncAgentSkillsMirror(runtime?: AgentRuntime): void {
  // Two sources contribute:
  //   1. Container-bundled NanoClaw skills at /home/node/.claude/skills/
  //      (agent-browser, vercel-cli, slack-formatting, etc.)
  //   2. Host plugin tree mounted RO at /workspace/plugins/, discovered via
  //      the same rules the host script applies (`.agents/skills/` preferred,
  //      Claude-only sub-plugins denied).
  // Defers to any pre-existing non-symlink content (host-side mounts or
  // operator-managed runtime installs).
  const containerSkillEntries: DiscoveredSkill[] = [];
  try {
    for (const entry of fs.readdirSync(CONTAINER_CLAUDE_SKILLS_DIR)) {
      const sd = path.join(CONTAINER_CLAUDE_SKILLS_DIR, entry);
      try {
        if (fs.statSync(sd).isDirectory() && fs.existsSync(path.join(sd, 'SKILL.md'))) {
          // Containment root for a bundled skill is the bundled-skills dir
          // itself: these ship in the image and have no plugin repository. The
          // image's own skills contain no symlinks today, so this changes
          // nothing about what they mirror.
          containerSkillEntries.push({
            name: entry,
            skillDir: sd,
            plugin: 'container-bundled',
            pluginRoot: CONTAINER_CLAUDE_SKILLS_DIR,
          });
        }
      } catch {
        continue;
      }
    }
  } catch {
    /* container skills dir missing */
  }

  // Codex loads ~/plugins natively (marketplace + `~/.codex/plugins/cache`, which is
  // symlinked into CODEX_HOME) — skills arrive namespaced `<plugin>:<skill>` WITH any
  // MCP server the plugin declares. Mirroring them here too would double-list every
  // skill unprefixed and MCP-less, which is exactly the duplication this mirror used to
  // cause. So for codex the mirror carries ONLY container-bundled NanoClaw skills
  // (agent-browser, welcome, …) — those are not plugins and have no native path.
  //
  // OpenCode has NO plugin loader at all, so the mirror remains its sole delivery for
  // plugin skills. Per-plugin routing (.nanoclaw-plugin.json `denySiblings`) is applied
  // inside discoverPortableSkills.
  const pluginSkills =
    runtime === 'codex'
      ? []
      : discoverPortableSkills(CONTAINER_PLUGINS_DIR, { runtime, excludePlugins: loadExcludedPlugins() });

  // Plugin skills first (preferred source), then container-bundled —
  // first occurrence wins by name.
  const merged = new Map<string, DiscoveredSkill>();
  for (const s of pluginSkills) merged.set(s.name, s);
  for (const s of containerSkillEntries) if (!merged.has(s.name)) merged.set(s.name, s);

  const result = syncDiscoveredSkillSymlinks(CONTAINER_AGENTS_SKILLS_DIR, [...merged.values()]);
  log(
    `~/.agents/skills/: ${merged.size} desired ` +
      `(${containerSkillEntries.length} container + ${pluginSkills.length} plugin) — ` +
      `created=${result.created.length} unchanged=${result.unchanged.length} ` +
      `removed=${result.removed.length} skipped=${result.skipped.length}`,
  );
  // Containment refusals: a skill dir or child resolving outside its own plugin
  // repository. Never silent — an operator seeing a skill go missing needs the
  // reason in the log rather than in a diff of the mirror.
  if (result.refused.length > 0) {
    log(
      `~/.agents/skills/: refused ${result.refused.length} path(s) outside their plugin: ${result.refused.join(', ')}`,
    );
  }
}
