/**
 * Peer-mode CODEX_HOME for a Claude/OpenCode container: `/home/node/.codex-runtime/`. Its only input from the host
 * CLI's Codex home is the auth.json symlink (OAuth refresh must persist there); config, MCP servers and plugins are
 * generated in-container, and agents/ links the host-populated group roster. `~/.codex/config.toml` can't hold them:
 * the host regenerates it on every spawn.
 */
import { spawnSync, type SpawnSyncReturns } from 'node:child_process';
import fs from 'fs';
import path from 'path';

import { loadExcludedPlugins } from './excluded-plugins.js';
import { isExcludedPluginPath, type ExcludedPlugins } from './plugin-exclusions.js';
import {
  readCodexConfigToml,
  writeCodexConfigToml,
  writeCodexConfigTomlAsserting,
} from './providers/codex-config-file.js';
import {
  type AppServer,
  buildCodexHooksJson,
  listCodexHooks,
  parseTomlTableHeader,
  renderCodexMcpServer,
  writeCodexHooksJson,
} from './providers/codex-app-server.js';
import {
  type CodexHookTrustEntry,
  classifyCodexHookList,
  collectCodexHookTrustEntries,
  codexHookTrustTables,
  collectPluginHookTrustEntries,
  formatCodexHookTrustProblem,
  mergeCodexHookTrustIntoToml,
} from './providers/codex-hook-trust.js';
import {
  type AgentRuntime,
  type DiscoveredSkill,
  discoverPortableSkills,
  readPluginDenySiblings,
  syncSkillSymlinks as syncDiscoveredSkillSymlinks,
} from './plugin-skill-discovery.js';
import type { McpServerConfig } from './providers/types.js';

export { readCodexConfigToml };

const HOST_CODEX_DIR = '/home/node/.codex';
const RUNTIME_CODEX_DIR = '/home/node/.codex-runtime';
/** Deliberately nonexistent: codex refuses to start on it instead of falling back to the default home. */
const FAILED_CODEX_HOME = '/nonexistent/codex-runtime-setup-failed';
const CONTAINER_CLAUDE_SKILLS_DIR = '/home/node/.claude/skills';
const CONTAINER_PLUGINS_DIR = '/workspace/plugins';
const CONTAINER_AGENTS_SKILLS_DIR = '/home/node/.agents/skills';

/** Parallel implementation of `buildContainerCodexConfig()` in src/providers/codex.ts: keep the two in sync. */
const CONTAINER_CODEX_CONFIG_BASE = [
  '# Generated by NanoClaw (codex-companion-setup.ts) — container-owned.',
  '# Rewritten on every spawn; MCP blocks below come from container wiring.',
  'sandbox_mode = "workspace-write"',
  'approval_policy = "on-request"',
  'approvals_reviewer = "auto_review"',
  'model_context_window = 400000',
  'model_auto_compact_token_limit = 360000',
  '',
  '[features]',
  'context_management = true',
  'hooks = true',
  'fast_mode = false',
  'memories = true',
  'goals = true',
  'multi_agent = true',
  '',
  '[agents]',
  // No `default_subagent_reasoning_effort`, matching src/providers/codex.ts. A plain literal on purpose:
  // src/provider-surfaces.test.ts evaluates this array in a bare `new Function` scope, so it may reference only
  // bindings that test supplies.
  'max_concurrent_threads_per_session = 5',
  '',
  ...['/workspace/agent', '/workspace/workgroup', '/workspace/worktrees', '/tmp'].flatMap((proj) => [
    `[projects."${proj}"]`,
    'trust_level = "trusted"',
    '',
  ]),
].join('\n');

const GROUP_CODEX_AGENTS_DIR = '/workspace/agent/.codex/agents';

function log(msg: string): void {
  console.error(`[codex-companion-setup] ${msg}`);
}

export function renderMcpServerForTest(name: string, config: McpServerConfig): string[] {
  return renderMcpServer(name, config);
}

export function buildRuntimeConfigForTest(mcpServers: Record<string, McpServerConfig>): string {
  return buildRuntimeConfig(mcpServers);
}

export function stripPluginsAndMarketplacesForTest(toml: string): string {
  return stripPluginsAndMarketplaces(toml);
}

function renderMcpServer(name: string, config: McpServerConfig): string[] {
  // The same renderer as writeCodexMcpConfigToml: one malformed entry makes
  // codex reject the file and drops every MCP server.
  if (config.type === 'sse') {
    throw new Error(`MCP server "${name}" uses deprecated SSE transport. Use type: "http" instead.`);
  }
  return renderCodexMcpServer(name, config);
}

function parseTomlString(raw: string): string {
  const m = raw.match(/^"((?:[^"\\]|\\.)*)"/);
  if (!m) return raw;
  return m[1].replace(/\\"/g, '"').replace(/\\\\/g, '\\');
}

function parseTomlInlineStringMap(raw: string): Record<string, string> {
  const map: Record<string, string> = {};
  const body = raw
    .trim()
    .replace(/^\{\s*/, '')
    .replace(/\s*\}$/, '');
  for (const part of splitTomlArray(body)) {
    const m = part.match(/^("((?:[^"\\]|\\.)*)"|[A-Za-z_][A-Za-z0-9_-]*)\s*=\s*(.+)$/);
    if (!m) continue;
    const key = m[2] !== undefined ? parseTomlString(m[1]) : m[1];
    map[key] = parseTomlString(m[3].trim());
  }
  return map;
}

function splitTomlArray(inside: string): string[] {
  const parts: string[] = [];
  let depth = 0;
  let buf = '';
  let inString = false;
  let escape = false;
  for (const ch of inside) {
    if (escape) {
      buf += ch;
      escape = false;
      continue;
    }
    if (ch === '\\') {
      buf += ch;
      escape = true;
      continue;
    }
    if (ch === '"') {
      inString = !inString;
      buf += ch;
      continue;
    }
    if (!inString) {
      if (ch === '[') depth++;
      if (ch === ']') depth--;
      if (ch === ',' && depth === 0) {
        parts.push(buf.trim());
        buf = '';
        continue;
      }
    }
    buf += ch;
  }
  if (buf.trim()) parts.push(buf.trim());
  return parts;
}

/** The host's config.toml contributes nothing: it leaked host-personal state into peer sessions. */
function buildRuntimeConfig(mcpServers: Record<string, McpServerConfig>): string {
  const mcpLines: string[] = [];
  for (const [name, config] of Object.entries(mcpServers)) {
    if (name.toLowerCase() === 'gitnexus') continue; // container-retired
    mcpLines.push(...renderMcpServer(name, config));
    mcpLines.push('');
  }
  return [CONTAINER_CODEX_CONFIG_BASE, '', '# --- nanoclaw runtime MCP servers ---', '', ...mcpLines].join('\n');
}

/** Host plugin tables are dropped, never rewritten: plugins are registered fresh from /workspace/plugins. */
function isPluginTable(tableName: string): boolean {
  return (
    tableName === 'plugins' ||
    tableName === 'marketplaces' ||
    tableName === 'plugin_marketplaces' ||
    tableName.startsWith('plugins.') ||
    tableName.startsWith('marketplaces.') ||
    tableName.startsWith('plugin_marketplaces.')
  );
}

function splitPluginsAndMarketplaces(toml: string): { base: string; plugins: string } {
  const base: string[] = [];
  const plugins: string[] = [];
  let inStrippedBlock = false;
  for (const line of toml.split('\n')) {
    const header = parseTomlTableHeader(line);
    if (header !== null) {
      inStrippedBlock = isPluginTable(header);
    }
    (inStrippedBlock ? plugins : base).push(line);
  }
  return { base: base.join('\n'), plugins: plugins.join('\n') };
}

function stripPluginsAndMarketplaces(toml: string): string {
  return splitPluginsAndMarketplaces(toml).base;
}

function projectCodexPluginConfig(primaryToml: string, targetToml: string): string {
  const primaryPlugins = splitPluginsAndMarketplaces(primaryToml).plugins.trim();
  const targetBase = stripPluginsAndMarketplaces(targetToml).trimEnd();
  return [targetBase, primaryPlugins].filter(Boolean).join('\n\n') + '\n';
}

export function projectCodexPluginConfigForTest(primaryToml: string, targetToml: string): string {
  return projectCodexPluginConfig(primaryToml, targetToml);
}

/**
 * Returning `null` would be a guard bypass: the caller would leave CODEX_HOME at the staged home, which has auth
 * but no guard chain. The sentinel disables only peer Codex; throwing would crash-loop every container under disk
 * pressure.
 */
function failClosed(what: string, err: unknown): string {
  const detail = err instanceof Error ? err.message : String(err);
  log(
    `FAIL-CLOSED: peer-mode Codex DISABLED for this container — ${what}: ${detail}. ` +
      `CODEX_HOME is set to the nonexistent sentinel ${FAILED_CODEX_HOME}, so \`codex exec\` will refuse ` +
      `to start rather than run unguarded against the staged ${HOST_CODEX_DIR}. ` +
      `The primary agent provider is unaffected. Most likely cause: no space / bad permissions on /home/node.`,
  );
  return FAILED_CODEX_HOME;
}

/**
 * Only plugins `planCodexPluginRegistration` registers are trusted; codex-hook-trust.ts says why plugin hooks are
 * trusted at all.
 */
function pluginHookTrustEntries(pluginsRoot: string): CodexHookTrustEntry[] {
  if (!fs.existsSync(pluginsRoot)) return [];
  const entries: CodexHookTrustEntry[] = [];
  for (const plan of planCodexPluginRegistration(pluginsRoot)) {
    if (plan.action !== 'register' || !plan.pluginDir || !plan.entryName || !plan.marketplaceName) continue;
    entries.push(
      ...collectPluginHookTrustEntries({
        pluginId: `${plan.entryName}@${plan.marketplaceName}`,
        dir: plan.pluginDir,
      }),
    );
  }
  return entries;
}

/** Shared by the writer and the verifier so the check cannot assert a different key set than was written. */
function generatedHookTrustEntries(codexHome: string, opts?: { emailGateTimeoutSec?: number }): CodexHookTrustEntry[] {
  return collectCodexHookTrustEntries(path.join(codexHome, 'hooks.json'), buildCodexHooksJson(opts).hooks);
}

/**
 * Throws (refusing the spawn) unless every generated guard handler is dispatchable, including when `hooks/list`
 * itself fails: the failure it catches is silent by construction. Plugin handlers are logged, not fatal.
 */
export async function verifyCodexHookTrust(
  server: AppServer,
  codexHome: string,
  opts?: { emailGateTimeoutSec?: number },
): Promise<void> {
  const expected = generatedHookTrustEntries(codexHome, opts).map((entry) => entry.key);
  if (expected.length === 0) {
    // buildCodexHooksJson always emits both events, so an empty set must fail rather than pass vacuously.
    throw new Error(
      `Codex hook trust verification: derived NO expected handler keys for ${codexHome} — ` +
        `refusing to spawn an app-server whose guard chain cannot be checked.`,
    );
  }

  let listed;
  try {
    listed = await listCodexHooks(server);
  } catch (err) {
    const detail = err instanceof Error ? err.message : String(err);
    log(
      `FAIL-CLOSED: could not read hooks/list from the app-server — the destructive-action guard chain ` +
        `cannot be proven live, so the spawn is refused: ${detail}`,
    );
    throw new Error(`Codex hook trust verification failed (hooks/list unavailable): ${detail}`);
  }

  const verdict = classifyCodexHookList(listed.entries, expected);
  for (const problem of verdict.plugin) {
    log(`Non-generated hook will NOT fire (reported, not fatal): ${formatCodexHookTrustProblem(problem)}`);
  }
  for (const warning of listed.warnings) log(`hooks/list warning: ${warning}`);
  for (const error of listed.errors) log(`hooks/list error: ${error}`);

  if (verdict.generated.length > 0) {
    const detail = verdict.generated.map(formatCodexHookTrustProblem).join('; ');
    log(
      `FAIL-CLOSED: ${verdict.generated.length} of ${expected.length} generated guard handler(s) in ${codexHome} ` +
        `would NEVER be dispatched by this codex — ${detail}. ` +
        `Refusing the spawn: a Codex session with an inert destructive-action guard is the exact silent ` +
        `state this check exists to make unreachable.`,
    );
    throw new Error(`Codex hook trust verification failed for ${codexHome}: ${detail}`);
  }

  log(
    `Hook trust verified live: ${verdict.generatedOk.length} generated guard handler(s) dispatchable in ${codexHome}`,
  );
}

/** Idempotent and keyed on the home passed in: safe to re-run after `codex plugin add` or an OAuth rotation. */
export function syncCodexHookTrust(
  codexHome: string,
  opts?: { emailGateTimeoutSec?: number; pluginsRoot?: string },
): void {
  const configPath = path.join(codexHome, 'config.toml');
  const entries = [
    ...generatedHookTrustEntries(codexHome, opts),
    ...pluginHookTrustEntries(opts?.pluginsRoot ?? CONTAINER_PLUGINS_DIR),
  ];
  try {
    fs.mkdirSync(codexHome, { recursive: true });
    // Asserting variant: the trust rows are the one table nothing else can restore.
    writeCodexConfigTomlAsserting(
      configPath,
      (existing) => mergeCodexHookTrustIntoToml(existing, entries),
      codexHookTrustTables(entries),
    );
  } catch (err) {
    // Must throw: swallowing leaves hooks.json with no trust entry, an inert guard, and callers that spawn anyway.
    const detail = err instanceof Error ? err.message : String(err);
    log(`FAILED to write hook trust to ${configPath} — Codex hooks would be UNTRUSTED and never fire: ${detail}`);
    throw new Error(`could not write Codex hook trust entries to ${configPath}: ${detail}`);
  }
  log(`Hook trust: ${entries.length} entry(ies) written to ${configPath}`);
}

/** Always call this instead of `writeCodexHooksJson`: a hooks.json without trust entries never runs. */
export function writeCodexHooksAndTrust(opts?: {
  emailGateTimeoutSec?: number;
  codexHome?: string;
  pluginsRoot?: string;
}): string {
  const home = writeCodexHooksJson(opts);
  syncCodexHookTrust(home, opts);
  return home;
}

/**
 * Returns `null` only when the codex auth mount is absent; every filesystem failure returns the FAILED_CODEX_HOME
 * sentinel instead (see `failClosed`).
 */
export function setupCodexRuntime(
  mcpServers: Record<string, McpServerConfig>,
  runtime: AgentRuntime = 'claude',
): string | null {
  const hostAuth = path.join(HOST_CODEX_DIR, 'auth.json');
  if (!fs.existsSync(hostAuth)) {
    log('Host codex auth not mounted — skipping CODEX_HOME runtime setup');
    return null;
  }

  try {
    fs.mkdirSync(RUNTIME_CODEX_DIR, { recursive: true });
  } catch (err) {
    return failClosed('could not create the runtime dir', err);
  }

  const runtimeAuth = path.join(RUNTIME_CODEX_DIR, 'auth.json');
  try {
    if (fs.existsSync(runtimeAuth) || fs.lstatSync(runtimeAuth, { throwIfNoEntry: false } as never)) {
      fs.unlinkSync(runtimeAuth);
    }
  } catch {
    /* not present — fine */
  }
  try {
    fs.symlinkSync(hostAuth, runtimeAuth);
  } catch (err) {
    return failClosed('could not symlink auth.json', err);
  }

  // Group-owned roster, never the host's ~/.codex/agents: host CLI config must not shape a container agent.
  const groupAgentsDir = GROUP_CODEX_AGENTS_DIR;
  const runtimeAgentsDir = path.join(RUNTIME_CODEX_DIR, 'agents');
  if (fs.existsSync(groupAgentsDir)) {
    try {
      try {
        fs.unlinkSync(runtimeAgentsDir);
      } catch {
        /* fresh */
      }
      fs.symlinkSync(groupAgentsDir, runtimeAgentsDir);
    } catch (err) {
      log(`Failed to symlink agents/: ${err instanceof Error ? err.message : String(err)}`);
    }
  }

  const runtimeConfigPath = path.join(RUNTIME_CODEX_DIR, 'config.toml');
  try {
    // `readBase: false`: nothing carries forward, so an unreadable previous file is no reason to disable peer Codex.
    writeCodexConfigToml(runtimeConfigPath, () => buildRuntimeConfig(mcpServers), { readBase: false });
  } catch (err) {
    return failClosed('could not write the merged config.toml', err);
  }

  // Peer `codex exec` commands bypass the parent's Bash hook, so the guard chain must be installed before the
  // runtime is exposed.
  try {
    writeCodexHooksAndTrust({ codexHome: RUNTIME_CODEX_DIR });
  } catch (err) {
    return failClosed('could not write the peer Codex hooks.json', err);
  }

  // Must run after config.toml is written: `codex plugin` mutates it in place.
  registerContainerCodexPlugins(RUNTIME_CODEX_DIR, runtime);

  // Re-sync after registration: `codex plugin add` rewrote config.toml, and new plugins' hooks are reachable only now.
  try {
    syncCodexHookTrust(RUNTIME_CODEX_DIR);
  } catch (err) {
    return failClosed('could not re-write the peer Codex hook trust after plugin registration', err);
  }

  // No skills re-sync here: without a runtime arg it would default to 'codex' and strip workflow-agents skills in
  // opencode containers.
  log(`CODEX_HOME runtime ready at ${RUNTIME_CODEX_DIR} (${Object.keys(mcpServers).length} MCP servers merged)`);
  return RUNTIME_CODEX_DIR;
}

function replaceWithDirectorySymlink(linkPath: string, targetPath: string): void {
  fs.rmSync(linkPath, { recursive: true, force: true });
  if (!fs.existsSync(targetPath)) return;
  fs.mkdirSync(path.dirname(linkPath), { recursive: true });
  fs.symlinkSync(targetPath, linkPath, 'dir');
}

/**
 * Fallback homes share the primary's derived plugin cache through symlinks; auth and rollout state stay
 * independent.
 */
export function setupCodexPrimaryRuntime(
  fallbackHomes: string[] = (process.env.CODEX_FALLBACK_HOMES ?? '')
    .split(':')
    .map((home) => home.trim())
    .filter(Boolean),
): { registered: string[]; skipped: string[]; errors: string[]; projectedFallbacks: string[] } {
  const registration = registerContainerCodexPlugins(HOST_CODEX_DIR, 'codex');
  // Recorded, not thrown: the spawn re-derives trust and refuses on failure, so a startup error must not
  // crash-loop the container.
  try {
    syncCodexHookTrust(HOST_CODEX_DIR);
  } catch (err) {
    registration.errors.push(
      `${HOST_CODEX_DIR}: hook trust sync failed — ${err instanceof Error ? err.message : String(err)}`,
    );
  }
  const projectedFallbacks: string[] = [];
  const primaryConfigPath = path.join(HOST_CODEX_DIR, 'config.toml');
  // Unreadable primary: skip the projection, since overwriting a fallback's config with nothing is unrecoverable.
  const primaryConfig = ((): string | null => {
    try {
      return readCodexConfigToml(primaryConfigPath);
    } catch (err) {
      registration.errors.push(
        `${primaryConfigPath}: unreadable — skipped projecting it into ${fallbackHomes.length} fallback home(s) ` +
          `rather than writing an empty config over them: ${err instanceof Error ? err.message : String(err)}`,
      );
      return null;
    }
  })();

  const projections = primaryConfig === null ? [] : fallbackHomes.map((home) => [home, primaryConfig] as const);

  for (const [fallbackHome, basePrimaryConfig] of projections) {
    try {
      fs.mkdirSync(fallbackHome, { recursive: true });
      replaceWithDirectorySymlink(path.join(fallbackHome, 'plugins'), path.join(HOST_CODEX_DIR, 'plugins'));
      replaceWithDirectorySymlink(
        path.join(fallbackHome, '.tmp', 'marketplaces'),
        path.join(HOST_CODEX_DIR, '.tmp', 'marketplaces'),
      );

      const fallbackConfigPath = path.join(fallbackHome, 'config.toml');
      writeCodexConfigToml(fallbackConfigPath, (fallbackConfig) =>
        projectCodexPluginConfig(basePrimaryConfig, fallbackConfig),
      );
      // Trust entries are keyed on the home's OWN hooks.json path, so the
      // projection cannot carry the primary's — derive them for this home.
      syncCodexHookTrust(fallbackHome);
      projectedFallbacks.push(fallbackHome);
    } catch (err) {
      registration.errors.push(
        `${fallbackHome}: fallback projection failed — ${err instanceof Error ? err.message : String(err)}`,
      );
    }
  }

  log(
    `Codex-primary plugin runtime: ${registration.registered.length} registered, ` +
      `${projectedFallbacks.length} fallback(s) projected, ${registration.errors.length} errors`,
  );
  return { ...registration, projectedFallbacks };
}

function isDirectorySafe(p: string): boolean {
  try {
    return fs.statSync(p).isDirectory();
  } catch {
    return false;
  }
}

/** From the manifest's `name`, never the folder name: `codex plugin add` hard-errors when they differ. */
function readCodexPluginEntryName(pluginDir: string): string | null {
  try {
    const raw = fs.readFileSync(path.join(pluginDir, '.codex-plugin', 'plugin.json'), 'utf-8');
    const parsed = JSON.parse(raw) as { name?: unknown };
    return typeof parsed.name === 'string' && parsed.name.trim() ? parsed.name : null;
  } catch {
    return null;
  }
}

function readCodexMarketplaceName(pluginDir: string): string | null {
  // Codex also accepts `.claude-plugin/marketplace.json`, which Claude-first marketplace monorepos ship.
  for (const rel of [
    path.join('.agents', 'plugins', 'marketplace.json'),
    path.join('.claude-plugin', 'marketplace.json'),
  ]) {
    try {
      const parsed = JSON.parse(fs.readFileSync(path.join(pluginDir, rel), 'utf-8')) as { name?: unknown };
      if (typeof parsed.name === 'string' && parsed.name.trim()) return parsed.name;
    } catch {
      /* try the next location */
    }
  }
  return null;
}

/** Only sub-dirs that exist AND carry a `.codex-plugin` manifest, so a sparse checkout registers only what it has. */
function findCodexSubPlugins(
  pluginDir: string,
  repoName: string,
  excluded: ExcludedPlugins,
): Array<{ dir: string; entryName: string }> {
  const found: Array<{ dir: string; entryName: string }> = [];
  const seen = new Set<string>();
  for (const container of [path.join(pluginDir, 'plugins'), pluginDir]) {
    if (!isDirectorySafe(container)) continue;
    // Exclusions are matched against the walk's own relative path, never a resolved one.
    const containerRel = container === pluginDir ? repoName : `${repoName}/plugins`;
    let subs: string[] = [];
    try {
      subs = fs.readdirSync(container);
    } catch {
      continue;
    }
    for (const sub of subs) {
      if (sub.startsWith('.')) continue;
      const dir = path.join(container, sub);
      if (isExcludedPluginPath(`${containerRel}/${sub}`, excluded)) continue;
      if (seen.has(dir) || !isDirectorySafe(dir)) continue;
      const entryName = readCodexPluginEntryName(dir);
      if (!entryName) continue;
      seen.add(dir);
      found.push({ dir, entryName });
    }
  }
  return found;
}

export interface CodexPluginRegistrationPlan {
  name: string;
  action: 'register' | 'skip';
  reason?: string;
  entryName?: string;
  marketplaceName?: string;
  /** `codex plugin marketplace add` target: a monorepo sub-plugin's marketplace is the repo root. */
  repoName?: string;
  /** Dir holding `.codex-plugin/plugin.json`: for a monorepo sub-plugin, the sub-directory. */
  pluginDir?: string;
}

/**
 * Top-level exclusions are already omitted from the mount by the host. Sub-plugin exclusions are honoured only
 * here, and since `pluginHookTrustEntries` keys off this plan, an excluded sub-plugin never gains a trust entry.
 */
export function planCodexPluginRegistration(
  pluginsRoot: string,
  excluded: ExcludedPlugins = loadExcludedPlugins(),
): CodexPluginRegistrationPlan[] {
  let entries: string[] = [];
  try {
    entries = fs.readdirSync(pluginsRoot);
  } catch {
    return [];
  }

  const plans: CodexPluginRegistrationPlan[] = [];
  for (const name of entries) {
    const dir = path.join(pluginsRoot, name);
    if (isExcludedPluginPath(name, excluded)) {
      plans.push({ name, action: 'skip', reason: 'excluded-by-config' });
      continue;
    }
    if (!isDirectorySafe(dir)) {
      plans.push({ name, action: 'skip', reason: 'not-a-directory' });
      continue;
    }
    if (readPluginDenySiblings(dir).has('codex')) {
      plans.push({ name, action: 'skip', reason: 'denied-for-codex' });
      continue;
    }
    const marketplaceName = readCodexMarketplaceName(dir);
    if (!marketplaceName) {
      plans.push({ name, action: 'skip', reason: 'no-marketplace-manifest' });
      continue;
    }
    const entryName = readCodexPluginEntryName(dir);
    if (entryName) {
      plans.push({ name, action: 'register', entryName, marketplaceName, repoName: name, pluginDir: dir });
      continue;
    }
    // Monorepo: each checked-out sub-plugin registers against the repo's marketplace (re-adding it is idempotent).
    const subs = findCodexSubPlugins(dir, name, excluded);
    if (subs.length === 0) {
      plans.push({ name, action: 'skip', reason: 'no-codex-plugin-manifest' });
      continue;
    }
    for (const sub of subs) {
      plans.push({
        name: `${name}/${sub.entryName}`,
        action: 'register',
        entryName: sub.entryName,
        marketplaceName,
        repoName: name,
        pluginDir: sub.dir,
      });
    }
  }
  return plans;
}

function describeSpawnFailure(result: SpawnSyncReturns<string>): string {
  if (result.error) return result.error.message;
  const stderr = (result.stderr ?? '').toString().trim();
  return stderr || `exit code ${result.status ?? 'unknown'}`;
}

/** Never throws: one bad plugin must not break container startup, so failures land in `errors`. */
export function registerContainerCodexPlugins(
  runtimeHome: string,
  runtime: AgentRuntime,
): { registered: string[]; skipped: string[]; errors: string[] } {
  const registered: string[] = [];
  const skipped: string[] = [];
  const errors: string[] = [];

  if (!fs.existsSync(CONTAINER_PLUGINS_DIR)) {
    return { registered, skipped, errors };
  }

  const plans = planCodexPluginRegistration(CONTAINER_PLUGINS_DIR);
  const env = { ...process.env, CODEX_HOME: runtimeHome };

  for (const plan of plans) {
    if (plan.action === 'skip') {
      skipped.push(plan.name);
      continue;
    }

    // Monorepo sub-plugins register against their REPO root, not the label path.
    const dir = path.join(CONTAINER_PLUGINS_DIR, plan.repoName ?? plan.name);
    const addMarketplace = spawnSync('codex', ['plugin', 'marketplace', 'add', dir], {
      env,
      timeout: 60_000,
      encoding: 'utf-8',
    });
    if (addMarketplace.status !== 0) {
      errors.push(`${plan.name}: marketplace add failed — ${describeSpawnFailure(addMarketplace)}`);
      continue;
    }

    const addPlugin = spawnSync('codex', ['plugin', 'add', `${plan.entryName}@${plan.marketplaceName}`], {
      env,
      timeout: 60_000,
      encoding: 'utf-8',
    });
    if (addPlugin.status !== 0) {
      errors.push(`${plan.name}: plugin add failed — ${describeSpawnFailure(addPlugin)}`);
      continue;
    }

    registered.push(plan.name);
  }

  log(
    `Container Codex plugin registration (runtime=${runtime}): ` +
      `${registered.length} registered, ${skipped.length} skipped, ${errors.length} errors` +
      (errors.length > 0 ? ` — ${errors.join('; ')}` : ''),
  );

  return { registered, skipped, errors };
}

/** Codex scans this dir (verified via `codex debug prompt-input`); needed for codex-primary and codex-as-peer. */
export function syncAgentSkillsMirror(runtime?: AgentRuntime): void {
  // Defers to any pre-existing non-symlink content (host-side mounts or operator-managed installs).
  const containerSkillEntries: DiscoveredSkill[] = [];
  try {
    for (const entry of fs.readdirSync(CONTAINER_CLAUDE_SKILLS_DIR)) {
      const sd = path.join(CONTAINER_CLAUDE_SKILLS_DIR, entry);
      try {
        if (fs.statSync(sd).isDirectory() && fs.existsSync(path.join(sd, 'SKILL.md'))) {
          // Bundled skills have no plugin repository, so the bundled-skills dir is their containment root.
          containerSkillEntries.push({
            name: entry,
            skillDir: sd,
            plugin: 'container-bundled',
            pluginRoot: CONTAINER_CLAUDE_SKILLS_DIR,
          });
        }
      } catch {
        continue;
      }
    }
  } catch {
    /* container skills dir missing */
  }

  // Codex loads plugin skills natively (namespaced, with their MCP servers); mirroring them too would double-list
  // them unprefixed and MCP-less. OpenCode has no plugin loader, so the mirror is its only delivery.
  const pluginSkills =
    runtime === 'codex'
      ? []
      : discoverPortableSkills(CONTAINER_PLUGINS_DIR, { runtime, excludePlugins: loadExcludedPlugins() });

  // First occurrence wins by name, so plugin skills take precedence over bundled ones.
  const merged = new Map<string, DiscoveredSkill>();
  for (const s of pluginSkills) merged.set(s.name, s);
  for (const s of containerSkillEntries) if (!merged.has(s.name)) merged.set(s.name, s);

  const result = syncDiscoveredSkillSymlinks(CONTAINER_AGENTS_SKILLS_DIR, [...merged.values()]);
  log(
    `~/.agents/skills/: ${merged.size} desired ` +
      `(${containerSkillEntries.length} container + ${pluginSkills.length} plugin) — ` +
      `created=${result.created.length} unchanged=${result.unchanged.length} ` +
      `removed=${result.removed.length} skipped=${result.skipped.length}`,
  );
  // Never silent: an operator seeing a skill go missing needs the reason in the log.
  if (result.refused.length > 0) {
    log(
      `~/.agents/skills/: refused ${result.refused.length} path(s) outside their plugin: ${result.refused.join(', ')}`,
    );
  }
}
