#!/usr/bin/env tsx
/**
 * Sync ~/.claude/CLAUDE.md → ~/.codex/AGENTS.md.
 *
 * CLAUDE.md is the canonical source of behavioral rules. Codex doesn't
 * resolve `@path` includes in AGENTS.md, so we flatten them here and
 * prepend a small Codex-specific peer-framing header.
 *
 * Usage:
 *   pnpm exec tsx scripts/sync-codex-agents-md.ts
 *
 * Idempotent — re-runs are safe. Suggested to invoke after editing
 * ~/.claude/CLAUDE.md or any file it @-includes.
 */
import fs from 'fs';
import os from 'os';
import path from 'path';

import { flattenClaudeMd } from '../src/agents-md-flatten.js';

const CODEX_PEER_HEADER = `<!-- Generated by scripts/sync-codex-agents-md.ts from ~/.claude/CLAUDE.md. Do not edit. -->

## Working as a Peer to Claude Code

You are usually invoked as a peer agent alongside Claude Code (on the host) or alongside container agents (inside NanoClaw). Claude treats you as a collaborator with equal authority, not as a black-box oracle. Behave accordingly:

- When Claude hands you a task, take real ownership of it — don't merely sketch a direction and bounce it back. If the task is well-bounded, finish it.
- When Claude hands you a review, be adversarial in good faith. Find real failure modes; don't manufacture nits to look thorough.
- When you disagree with Claude, say so plainly with evidence. Claude's instructions tell it to treat your feedback as hypotheses, not orders — so do likewise with its assumptions.

---

`;

function main(): void {
  const claudeMd = path.join(os.homedir(), '.claude', 'CLAUDE.md');
  if (!fs.existsSync(claudeMd)) {
    console.error(`Source not found: ${claudeMd}`);
    process.exit(1);
  }

  const flattened = flattenClaudeMd(claudeMd);
  const output = CODEX_PEER_HEADER + flattened;

  const target = path.join(os.homedir(), '.codex', 'AGENTS.md');
  fs.mkdirSync(path.dirname(target), { recursive: true });

  const tmp = `${target}.tmp-${process.pid}`;
  fs.writeFileSync(tmp, output);
  fs.renameSync(tmp, target);

  console.log(`Wrote ${target} (${output.length} bytes, ${output.split('\n').length} lines)`);
}

main();
