/**
 * Reusable Codex-sync functions.
 *
 * Both the host-side CLI scripts (`scripts/sync-codex-*.ts`) and the
 * watcher daemon (`src/codex-sync-watcher.ts`) call these. Splitting them
 * out of the CLI shims lets the watcher run sync in-process — every
 * spawned `pnpm exec tsx` adds ~1s and ~200MB Node startup, which is
 * unacceptable when the daemon may fire many times per day.
 */
import fs from 'fs';
import os from 'os';
import path from 'path';

import { flattenClaudeMd } from './agents-md-flatten.js';
import { formatCodexAgentToml, isManagedToml, parseClaudeAgentMd } from './claude-agent-md.js';
import { discoverPortableSkills, syncSkillSymlinks } from './plugin-skill-discovery.js';

const CODEX_PEER_HEADER = `<!-- Generated by scripts/sync-codex-agents-md.ts from ~/.claude/CLAUDE.md. Do not edit. -->

## Working as a Peer to Claude Code

You are usually invoked as a peer agent alongside Claude Code (on the host) or alongside container agents (inside NanoClaw). Claude treats you as a collaborator with equal authority, not as a black-box oracle. Behave accordingly:

- When Claude hands you a task, take real ownership of it — don't merely sketch a direction and bounce it back. If the task is well-bounded, finish it.
- When Claude hands you a review, be adversarial in good faith. Find real failure modes; don't manufacture nits to look thorough.
- When you disagree with Claude, say so plainly with evidence. Claude's instructions tell it to treat your feedback as hypotheses, not orders — so do likewise with its assumptions.

---

`;

export interface AgentsMdSyncResult {
  target: string;
  bytes: number;
  lines: number;
  /** True when the new content differs from the old (write happened). */
  changed: boolean;
}

/**
 * Regenerate `~/.codex/AGENTS.md` from `~/.claude/CLAUDE.md`.
 *
 * - Flattens every `@path` include inline (Codex doesn't expand them).
 * - Prepends the peer-framing header so Codex knows it's working alongside Claude.
 * - Atomic write via tmp+rename.
 * - Skips the write if content is byte-identical to the existing file (idempotent on rerun).
 */
export function syncCodexAgentsMd(): AgentsMdSyncResult {
  const claudeMd = path.join(os.homedir(), '.claude', 'CLAUDE.md');
  if (!fs.existsSync(claudeMd)) {
    throw new Error(`Source not found: ${claudeMd}`);
  }

  const flattened = flattenClaudeMd(claudeMd);
  const output = CODEX_PEER_HEADER + flattened;

  const target = path.join(os.homedir(), '.codex', 'AGENTS.md');
  fs.mkdirSync(path.dirname(target), { recursive: true });

  let existing = '';
  try {
    existing = fs.readFileSync(target, 'utf-8');
  } catch {
    /* missing */
  }
  if (existing === output) {
    return { target, bytes: output.length, lines: output.split('\n').length, changed: false };
  }

  const tmp = `${target}.tmp-${process.pid}`;
  fs.writeFileSync(tmp, output);
  fs.renameSync(tmp, target);

  return { target, bytes: output.length, lines: output.split('\n').length, changed: true };
}

export interface PluginSkillsSyncResult {
  target: string;
  discovered: number;
  created: string[];
  removed: string[];
  unchanged: string[];
  skipped: string[];
}

/**
 * Walk `~/plugins/` and sync portable skills into `~/.agents/skills/`.
 *
 * - Materializes mirror dirs (real dir + real `SKILL.md` copy + symlinked subdirs).
 * - Defers to native installs (e.g. dirs written by `gitnexus setup`).
 * - Idempotent.
 */
export function syncCodexPluginSkills(): PluginSkillsSyncResult {
  const pluginsRoot = path.join(os.homedir(), 'plugins');
  const agentsSkills = path.join(os.homedir(), '.agents', 'skills');

  const discovered = discoverPortableSkills(pluginsRoot);
  const result = syncSkillSymlinks(agentsSkills, discovered);

  return {
    target: agentsSkills,
    discovered: discovered.length,
    ...result,
  };
}

export interface SubagentsSyncResult {
  /** Every Codex agents/ dir we wrote into (global + per-group siblings). */
  targets: string[];
  /** Distinct Claude `.md` subagents found at the source. */
  discovered: number;
  /** Per-target file write counts, summed across every target. A 6-agent
   * sync across 2 targets where everything was newly populated reports 12
   * writes; a subsequent idempotent re-run reports 0. */
  writes: number;
  /** Per-target file unchanged counts, summed. */
  unchangedFiles: number;
  /** Per-target file removals, summed (stale managed TOMLs cleaned up). */
  removedFiles: number;
  /** Agent names that had unmanaged TOMLs in at least one target — skipped
   * everywhere they collided. */
  skipped: string[];
}

/**
 * Walk every plugin agents/ dir and `~/.claude/agents/` (Claude personal scope)
 * and emit a Codex TOML for each `<name>.md`. Output written to BOTH
 * `~/.codex/agents/` (global default) AND every `~/.codex-<folder>/agents/`
 * that has an `auth.json` (per-group sibling codex accounts, e.g. illysium-codex,
 * madison-reed-codex). Per-group siblings mount their own `~/.codex-<folder>/`
 * into the container instead of the global `~/.codex/`, so the global write
 * alone wouldn't reach them.
 *
 * Idempotent. Files this sync wrote carry the `# managed by nanoclaw codex-sync`
 * marker; pre-existing TOMLs without it are left alone (manually-authored
 * subagents survive). Source-removed agents have their managed TOML cleaned up.
 *
 * Run by the sync watcher daemon on any `agents/*.md` change and by the
 * one-shot `pnpm exec tsx scripts/sync-codex-subagents.ts` script.
 */
export function syncCodexSubagents(): SubagentsSyncResult {
  const sources = discoverClaudeSubagents();
  const targetDirs = discoverCodexAgentTargets();
  let writes = 0;
  let unchangedFiles = 0;
  let removedFiles = 0;
  const skippedSet = new Set<string>();

  for (const target of targetDirs) {
    fs.mkdirSync(target, { recursive: true });
    const result = syncOneCodexAgentsDir(target, sources);
    writes += result.created.length;
    unchangedFiles += result.unchanged.length;
    removedFiles += result.removed.length;
    for (const s of result.skipped) skippedSet.add(s);
  }

  return {
    targets: targetDirs,
    discovered: sources.length,
    writes,
    unchangedFiles,
    removedFiles,
    skipped: [...skippedSet],
  };
}

interface OneDirResult {
  created: string[];
  unchanged: string[];
  removed: string[];
  skipped: string[];
}

function syncOneCodexAgentsDir(target: string, sources: DiscoveredSubagent[]): OneDirResult {
  const created: string[] = [];
  const unchanged: string[] = [];
  const removed: string[] = [];
  const skipped: string[] = [];

  const desiredTomls = new Set<string>();

  for (const src of sources) {
    const tomlPath = path.join(target, `${src.name}.toml`);
    desiredTomls.add(`${src.name}.toml`);

    if (fs.existsSync(tomlPath)) {
      const existing = fs.readFileSync(tomlPath, 'utf-8');
      if (!isManagedToml(existing)) {
        skipped.push(src.name);
        continue;
      }
    }

    let agentText: string;
    try {
      agentText = fs.readFileSync(src.path, 'utf-8');
    } catch {
      continue;
    }
    const parsed = parseClaudeAgentMd(agentText);
    if (!parsed) {
      skipped.push(src.name);
      continue;
    }

    const newContent = formatCodexAgentToml(parsed);
    let existing = '';
    try {
      existing = fs.readFileSync(tomlPath, 'utf-8');
    } catch {
      /* fresh write */
    }
    if (existing === newContent) {
      unchanged.push(src.name);
      continue;
    }
    fs.writeFileSync(tomlPath, newContent);
    created.push(src.name);
  }

  for (const entry of fs.readdirSync(target)) {
    if (!entry.endsWith('.toml')) continue;
    if (desiredTomls.has(entry)) continue;
    const filePath = path.join(target, entry);
    let content: string;
    try {
      content = fs.readFileSync(filePath, 'utf-8');
    } catch {
      continue;
    }
    if (!isManagedToml(content)) continue;
    fs.unlinkSync(filePath);
    removed.push(entry.replace(/\.toml$/, ''));
  }

  return { created, unchanged, removed, skipped };
}

/**
 * Find every Codex agents/ output directory. Always includes the global
 * `~/.codex/agents/`. Adds `~/.codex-<folder>/agents/` for every per-group
 * sibling dir that has an `auth.json` (so we don't write into half-set-up
 * siblings).
 */
function discoverCodexAgentTargets(): string[] {
  const home = os.homedir();
  const targets: string[] = [path.join(home, '.codex', 'agents')];

  let entries: fs.Dirent[];
  try {
    entries = fs.readdirSync(home, { withFileTypes: true });
  } catch {
    return targets;
  }

  for (const entry of entries) {
    if (!entry.isDirectory()) continue;
    if (!entry.name.startsWith('.codex-')) continue;
    const auth = path.join(home, entry.name, 'auth.json');
    if (!fs.existsSync(auth)) continue;
    targets.push(path.join(home, entry.name, 'agents'));
  }

  return targets;
}

interface DiscoveredSubagent {
  name: string;
  path: string;
  source: 'plugin' | 'personal';
}

/**
 * Find Claude-format subagent `.md` files in two locations:
 *   1. `~/plugins/<plugin>/[plugins/<sub>/]agents/*.md`
 *   2. `~/.claude/agents/*.md` (personal scope)
 *
 * First-occurrence-by-name wins, with personal scope outranking plugins so a
 * user-authored override beats a plugin-shipped default. Runtime-specific
 * dirs (`.claude/`, `.cursor/`, `.codex/`, etc.) under a plugin root are
 * skipped — those are runtime-specific copies; we want the canonical
 * Claude `.md` shape only. Hidden dirs (starting with `.`) and `deprecated/`
 * dirs are skipped too.
 */
function discoverClaudeSubagents(): DiscoveredSubagent[] {
  const home = os.homedir();
  const seen = new Map<string, DiscoveredSubagent>();

  // Personal scope first — these override plugin defaults.
  const personalDir = path.join(home, '.claude', 'agents');
  if (fs.existsSync(personalDir)) {
    for (const f of fs.readdirSync(personalDir)) {
      if (!f.endsWith('.md')) continue;
      const name = f.replace(/\.md$/, '');
      seen.set(name, { name, path: path.join(personalDir, f), source: 'personal' });
    }
  }

  // Plugin tree.
  const pluginsRoot = path.join(home, 'plugins');
  if (fs.existsSync(pluginsRoot)) {
    for (const plugin of fs.readdirSync(pluginsRoot)) {
      if (plugin.startsWith('.')) continue;
      walkPluginAgents(path.join(pluginsRoot, plugin), seen);
    }
  }

  return [...seen.values()];
}

function walkPluginAgents(dir: string, seen: Map<string, DiscoveredSubagent>, depth = 0): void {
  if (depth > 3) return;
  let entries: fs.Dirent[];
  try {
    entries = fs.readdirSync(dir, { withFileTypes: true });
  } catch {
    return;
  }
  for (const entry of entries) {
    if (entry.name.startsWith('.')) continue;
    if (entry.name === 'deprecated') continue;
    if (entry.name === 'node_modules') continue;
    if (!entry.isDirectory()) continue;
    const childPath = path.join(dir, entry.name);
    if (entry.name === 'agents') {
      // Found an agents/ dir — collect every `<name>.md` here, then keep
      // walking so deeper agents/ dirs (e.g. nested sub-plugins) are still
      // discovered. First-by-name still wins overall.
      for (const file of fs.readdirSync(childPath)) {
        if (!file.endsWith('.md')) continue;
        const name = file.replace(/\.md$/, '');
        if (seen.has(name)) continue;
        seen.set(name, { name, path: path.join(childPath, file), source: 'plugin' });
      }
      continue;
    }
    walkPluginAgents(childPath, seen, depth + 1);
  }
}
