/**
 * Reusable Codex-sync functions.
 *
 * Both the host-side CLI scripts (`scripts/sync-codex-*.ts`) and the
 * watcher daemon (`src/codex-sync-watcher.ts`) call these. Splitting them
 * out of the CLI shims lets the watcher run sync in-process — every
 * spawned `pnpm exec tsx` adds ~1s and ~200MB Node startup, which is
 * unacceptable when the daemon may fire many times per day.
 */
import fs from 'fs';
import os from 'os';
import path from 'path';

import { flattenClaudeMd } from './agents-md-flatten.js';
import { discoverPortableSkills, syncSkillSymlinks } from './plugin-skill-discovery.js';

const CODEX_PEER_HEADER = `<!-- Generated by scripts/sync-codex-agents-md.ts from ~/.claude/CLAUDE.md. Do not edit. -->

## Working as a Peer to Claude Code

You are usually invoked as a peer agent alongside Claude Code (on the host) or alongside container agents (inside NanoClaw). Claude treats you as a collaborator with equal authority, not as a black-box oracle. Behave accordingly:

- When Claude hands you a task, take real ownership of it — don't merely sketch a direction and bounce it back. If the task is well-bounded, finish it.
- When Claude hands you a review, be adversarial in good faith. Find real failure modes; don't manufacture nits to look thorough.
- When you disagree with Claude, say so plainly with evidence. Claude's instructions tell it to treat your feedback as hypotheses, not orders — so do likewise with its assumptions.

---

`;

export interface AgentsMdSyncResult {
  target: string;
  bytes: number;
  lines: number;
  /** True when the new content differs from the old (write happened). */
  changed: boolean;
}

/**
 * Regenerate `~/.codex/AGENTS.md` from `~/.claude/CLAUDE.md`.
 *
 * - Flattens every `@path` include inline (Codex doesn't expand them).
 * - Prepends the peer-framing header so Codex knows it's working alongside Claude.
 * - Atomic write via tmp+rename.
 * - Skips the write if content is byte-identical to the existing file (idempotent on rerun).
 */
export function syncCodexAgentsMd(): AgentsMdSyncResult {
  const claudeMd = path.join(os.homedir(), '.claude', 'CLAUDE.md');
  if (!fs.existsSync(claudeMd)) {
    throw new Error(`Source not found: ${claudeMd}`);
  }

  const flattened = flattenClaudeMd(claudeMd);
  const output = CODEX_PEER_HEADER + flattened;

  const target = path.join(os.homedir(), '.codex', 'AGENTS.md');
  fs.mkdirSync(path.dirname(target), { recursive: true });

  let existing = '';
  try {
    existing = fs.readFileSync(target, 'utf-8');
  } catch {
    /* missing */
  }
  if (existing === output) {
    return { target, bytes: output.length, lines: output.split('\n').length, changed: false };
  }

  const tmp = `${target}.tmp-${process.pid}`;
  fs.writeFileSync(tmp, output);
  fs.renameSync(tmp, target);

  return { target, bytes: output.length, lines: output.split('\n').length, changed: true };
}

export interface PluginSkillsSyncResult {
  target: string;
  discovered: number;
  created: string[];
  removed: string[];
  unchanged: string[];
  skipped: string[];
}

/**
 * Walk `~/plugins/` and sync portable skills into `~/.agents/skills/`.
 *
 * - Materializes mirror dirs (real dir + real `SKILL.md` copy + symlinked subdirs).
 * - Defers to native installs (e.g. dirs written by `gitnexus setup`).
 * - Idempotent.
 */
export function syncCodexPluginSkills(): PluginSkillsSyncResult {
  const pluginsRoot = path.join(os.homedir(), 'plugins');
  const agentsSkills = path.join(os.homedir(), '.agents', 'skills');

  const discovered = discoverPortableSkills(pluginsRoot);
  const result = syncSkillSymlinks(agentsSkills, discovered);

  return {
    target: agentsSkills,
    discovered: discovered.length,
    ...result,
  };
}
