/**
 * Reusable Codex-sync functions.
 *
 * Both the host-side CLI scripts (`scripts/sync-codex-*.ts`) and the
 * watcher daemon (`src/codex-sync-watcher.ts`) call these. Splitting them
 * out of the CLI shims lets the watcher run sync in-process — every
 * spawned `pnpm exec tsx` adds ~1s and ~200MB Node startup, which is
 * unacceptable when the daemon may fire many times per day.
 */
import fs from 'fs';
import os from 'os';
import path from 'path';

import { flattenClaudeMd } from './agents-md-flatten.js';
import { formatCodexAgentToml, isManagedToml, parseClaudeAgentMd } from './claude-agent-md.js';
import { discoverPortableSkills, syncSkillSymlinks } from './plugin-skill-discovery.js';

const CODEX_PEER_HEADER = `<!-- Generated by scripts/sync-codex-agents-md.ts from ~/.claude/CLAUDE.md. Do not edit. -->

## Working as a Peer to Claude Code

You are usually invoked as a peer agent alongside Claude Code (on the host) or alongside container agents (inside NanoClaw). Claude treats you as a collaborator with equal authority, not as a black-box oracle. Behave accordingly:

- When Claude hands you a task, take real ownership of it — don't merely sketch a direction and bounce it back. If the task is well-bounded, finish it.
- When Claude hands you a review, be adversarial in good faith. Find real failure modes; don't manufacture nits to look thorough.
- When you disagree with Claude, say so plainly with evidence. Claude's instructions tell it to treat your feedback as hypotheses, not orders — so do likewise with its assumptions.

---

`;

export interface AgentsMdSyncResult {
  target: string;
  bytes: number;
  lines: number;
  /** True when the new content differs from the old (write happened). */
  changed: boolean;
}

/**
 * Regenerate `~/.codex/AGENTS.md` from `~/.claude/CLAUDE.md`.
 *
 * - Flattens every `@path` include inline (Codex doesn't expand them).
 * - Prepends the peer-framing header so Codex knows it's working alongside Claude.
 * - Atomic write via tmp+rename.
 * - Skips the write if content is byte-identical to the existing file (idempotent on rerun).
 */
export function syncCodexAgentsMd(): AgentsMdSyncResult {
  const claudeMd = path.join(os.homedir(), '.claude', 'CLAUDE.md');
  if (!fs.existsSync(claudeMd)) {
    throw new Error(`Source not found: ${claudeMd}`);
  }

  const flattened = flattenClaudeMd(claudeMd);
  const output = CODEX_PEER_HEADER + flattened;

  const target = path.join(os.homedir(), '.codex', 'AGENTS.md');
  fs.mkdirSync(path.dirname(target), { recursive: true });

  let existing = '';
  try {
    existing = fs.readFileSync(target, 'utf-8');
  } catch {
    /* missing */
  }
  if (existing === output) {
    return { target, bytes: output.length, lines: output.split('\n').length, changed: false };
  }

  const tmp = `${target}.tmp-${process.pid}`;
  fs.writeFileSync(tmp, output);
  fs.renameSync(tmp, target);

  return { target, bytes: output.length, lines: output.split('\n').length, changed: true };
}

export interface PluginSkillsSyncResult {
  target: string;
  discovered: number;
  created: string[];
  removed: string[];
  unchanged: string[];
  skipped: string[];
}

/**
 * Walk `~/plugins/` and sync portable skills into `~/.agents/skills/`.
 *
 * - Materializes mirror dirs (real dir + real `SKILL.md` copy + symlinked subdirs).
 * - Defers to native installs (e.g. dirs written by `gitnexus setup`).
 * - Idempotent.
 */
export function syncCodexPluginSkills(): PluginSkillsSyncResult {
  const pluginsRoot = path.join(os.homedir(), 'plugins');
  const agentsSkills = path.join(os.homedir(), '.agents', 'skills');

  const discovered = discoverPortableSkills(pluginsRoot);
  const result = syncSkillSymlinks(agentsSkills, discovered);

  return {
    target: agentsSkills,
    discovered: discovered.length,
    ...result,
  };
}

export interface SubagentsSyncResult {
  /** Every Codex agents/ dir we wrote into (global + per-group siblings). */
  targets: string[];
  /** Distinct Claude `.md` subagents found at the source. */
  discovered: number;
  /** Per-target file write counts, summed across every target. A 6-agent
   * sync across 2 targets where everything was newly populated reports 12
   * writes; a subsequent idempotent re-run reports 0. */
  writes: number;
  /** Per-target file unchanged counts, summed. */
  unchangedFiles: number;
  /** Per-target file removals, summed (stale managed TOMLs cleaned up). */
  removedFiles: number;
  /** Agent names that had unmanaged TOMLs in at least one target — skipped
   * everywhere they collided. */
  skipped: string[];
}

/**
 * Walk every plugin agents/ dir and `~/.claude/agents/` (Claude personal scope)
 * and emit a Codex TOML for each `<name>.md`. Output written to BOTH
 * `~/.codex/agents/` (global default) AND every `~/.codex-<folder>/agents/`
 * that has an `auth.json` (per-group sibling codex accounts, e.g. illysium-codex,
 * madison-reed-codex). Per-group siblings mount their own `~/.codex-<folder>/`
 * into the container instead of the global `~/.codex/`, so the global write
 * alone wouldn't reach them.
 *
 * Idempotent. Files this sync wrote carry the `# managed by nanoclaw codex-sync`
 * marker; pre-existing TOMLs without it are left alone (manually-authored
 * subagents survive). Source-removed agents have their managed TOML cleaned up.
 *
 * Run by the sync watcher daemon on any `agents/*.md` change and by the
 * one-shot `pnpm exec tsx scripts/sync-codex-subagents.ts` script.
 */
export function syncCodexSubagents(): SubagentsSyncResult {
  const sources = discoverClaudeSubagents();
  const targetDirs = discoverCodexAgentTargets();
  let writes = 0;
  let unchangedFiles = 0;
  let removedFiles = 0;
  const skippedSet = new Set<string>();

  for (const target of targetDirs) {
    fs.mkdirSync(target, { recursive: true });
    const result = syncOneCodexAgentsDir(target, sources);
    writes += result.created.length;
    unchangedFiles += result.unchanged.length;
    removedFiles += result.removed.length;
    for (const s of result.skipped) skippedSet.add(s);
  }

  return {
    targets: targetDirs,
    discovered: sources.length,
    writes,
    unchangedFiles,
    removedFiles,
    skipped: [...skippedSet],
  };
}

interface ParsedTomlBlock {
  table: string;
  name: string;
  values: Map<string, string>;
}

interface MarketplacePlugin {
  marketplace: string;
  plugin: string;
  sourceRoot: string;
  pluginRoot: string;
  cacheRoot: string;
  cachePath: string;
  enabled: boolean;
}

export interface CodexLocalMarketplacePluginCacheSyncResult {
  target: string;
  marketplaces: number;
  installed: string[];
  updated: string[];
  removed: string[];
  skipped: string[];
  errors: string[];
}

/**
 * Materialize enabled Codex marketplace plugins into Codex's installed
 * plugin cache.
 *
 * `codex plugin marketplace add ...` records the marketplace source, but active
 * prompt assembly reads enabled plugin skills from
 * `~/.codex/plugins/cache/<marketplace>/<plugin>/<install-id>/`. The TUI can
 * install plugins into that cache; host-managed automation needs the same
 * cache shape so version bumps and skill edits are visible to Codex and to
 * mounted container runtimes.
 */
export function syncCodexLocalMarketplacePluginCache(): CodexLocalMarketplacePluginCacheSyncResult {
  const home = os.homedir();
  const codexDir = path.join(home, '.codex');
  const target = path.join(codexDir, 'plugins', 'cache');
  const configPath = path.join(codexDir, 'config.toml');
  const result: CodexLocalMarketplacePluginCacheSyncResult = {
    target,
    marketplaces: 0,
    installed: [],
    updated: [],
    removed: [],
    skipped: [],
    errors: [],
  };

  let config: string;
  try {
    config = fs.readFileSync(configPath, 'utf-8');
  } catch {
    result.skipped.push(`${configPath}:missing`);
    return result;
  }

  const blocks = parseTomlBlocks(config);
  const enabledPlugins = new Set(
    blocks.filter((b) => b.table === 'plugins' && tomlBool(b.values.get('enabled')) === true).map((b) => b.name),
  );

  const marketplacePlugins: MarketplacePlugin[] = [];
  for (const block of blocks) {
    if (block.table !== 'marketplaces') continue;
    const sourceType = tomlString(block.values.get('source_type'));
    if (sourceType !== 'local' && sourceType !== 'git') continue;

    const sourceRoot = resolveMarketplaceSourceRoot(block, sourceType, codexDir, home, result);
    if (!sourceRoot) {
      continue;
    }

    const marketplacePath = path.join(sourceRoot, '.agents', 'plugins', 'marketplace.json');
    let marketplace: MarketplaceJson;
    try {
      marketplace = JSON.parse(fs.readFileSync(marketplacePath, 'utf-8')) as MarketplaceJson;
    } catch (err) {
      result.errors.push(`${block.name}:read-marketplace:${err instanceof Error ? err.message : String(err)}`);
      continue;
    }
    result.marketplaces += 1;

    for (const entry of marketplace.plugins ?? []) {
      const pluginName = entry?.name;
      const entrySource = entry?.source;
      if (!pluginName || entrySource?.source !== 'local' || !entrySource.path) {
        result.skipped.push(`${block.name}:unsupported-entry`);
        continue;
      }
      const pluginRoot = path.resolve(sourceRoot, entrySource.path);
      if (!isInsidePath(sourceRoot, pluginRoot)) {
        result.skipped.push(`${block.name}/${pluginName}:outside-marketplace-root`);
        continue;
      }
      if (!fs.existsSync(path.join(pluginRoot, '.codex-plugin', 'plugin.json'))) {
        result.skipped.push(`${block.name}/${pluginName}:missing-plugin-json`);
        continue;
      }
      const cacheRoot = path.join(target, block.name, pluginName);
      marketplacePlugins.push({
        marketplace: block.name,
        plugin: pluginName,
        sourceRoot,
        pluginRoot,
        cacheRoot,
        cachePath: path.join(cacheRoot, sourceType === 'local' ? 'local' : marketplaceInstallId(block)),
        enabled: enabledPlugins.has(`${pluginName}@${block.name}`),
      });
    }
  }

  for (const plugin of marketplacePlugins) {
    if (!plugin.enabled) {
      result.skipped.push(`${plugin.plugin}@${plugin.marketplace}:disabled`);
      continue;
    }
    try {
      const existed = fs.existsSync(plugin.cachePath);
      replaceDirectory(plugin.pluginRoot, plugin.cachePath);
      (existed ? result.updated : result.installed).push(`${plugin.plugin}@${plugin.marketplace}`);
    } catch (err) {
      result.errors.push(
        `${plugin.plugin}@${plugin.marketplace}:copy:${err instanceof Error ? err.message : String(err)}`,
      );
    }
  }

  const desiredCachePaths = new Set(marketplacePlugins.filter((p) => p.enabled).map((p) => path.resolve(p.cachePath)));
  for (const plugin of marketplacePlugins) {
    const cacheRoot = path.resolve(plugin.cacheRoot);
    if (!isInsidePath(target, cacheRoot) || !fs.existsSync(cacheRoot)) continue;
    let entries: fs.Dirent[];
    try {
      entries = fs.readdirSync(cacheRoot, { withFileTypes: true });
    } catch {
      continue;
    }
    for (const entry of entries) {
      if (!entry.isDirectory()) continue;
      const entryPath = path.resolve(cacheRoot, entry.name);
      if (desiredCachePaths.has(entryPath)) continue;
      if (!isInsidePath(target, entryPath)) continue;
      fs.rmSync(entryPath, { recursive: true, force: true });
      result.removed.push(`${plugin.plugin}@${plugin.marketplace}/${entry.name}`);
    }
  }

  return result;
}

interface OneDirResult {
  created: string[];
  unchanged: string[];
  removed: string[];
  skipped: string[];
}

function syncOneCodexAgentsDir(target: string, sources: DiscoveredSubagent[]): OneDirResult {
  const created: string[] = [];
  const unchanged: string[] = [];
  const removed: string[] = [];
  const skipped: string[] = [];

  const desiredTomls = new Set<string>();

  for (const src of sources) {
    const tomlPath = path.join(target, `${src.name}.toml`);
    desiredTomls.add(`${src.name}.toml`);

    if (fs.existsSync(tomlPath)) {
      const existing = fs.readFileSync(tomlPath, 'utf-8');
      if (!isManagedToml(existing)) {
        skipped.push(src.name);
        continue;
      }
    }

    let agentText: string;
    try {
      agentText = fs.readFileSync(src.path, 'utf-8');
    } catch {
      continue;
    }
    const parsed = parseClaudeAgentMd(agentText);
    if (!parsed) {
      skipped.push(src.name);
      continue;
    }

    const newContent = formatCodexAgentToml(parsed);
    let existing = '';
    try {
      existing = fs.readFileSync(tomlPath, 'utf-8');
    } catch {
      /* fresh write */
    }
    if (existing === newContent) {
      unchanged.push(src.name);
      continue;
    }
    fs.writeFileSync(tomlPath, newContent);
    created.push(src.name);
  }

  for (const entry of fs.readdirSync(target)) {
    if (!entry.endsWith('.toml')) continue;
    if (desiredTomls.has(entry)) continue;
    const filePath = path.join(target, entry);
    let content: string;
    try {
      content = fs.readFileSync(filePath, 'utf-8');
    } catch {
      continue;
    }
    if (!isManagedToml(content)) continue;
    fs.unlinkSync(filePath);
    removed.push(entry.replace(/\.toml$/, ''));
  }

  return { created, unchanged, removed, skipped };
}

/**
 * Find every Codex agents/ output directory. Always includes the global
 * `~/.codex/agents/`. Adds `~/.codex-<folder>/agents/` for every per-group
 * sibling dir that has an `auth.json` (so we don't write into half-set-up
 * siblings).
 */
function discoverCodexAgentTargets(): string[] {
  const home = os.homedir();
  const targets: string[] = [path.join(home, '.codex', 'agents')];

  let entries: fs.Dirent[];
  try {
    entries = fs.readdirSync(home, { withFileTypes: true });
  } catch {
    return targets;
  }

  for (const entry of entries) {
    if (!entry.isDirectory()) continue;
    if (!entry.name.startsWith('.codex-')) continue;
    const auth = path.join(home, entry.name, 'auth.json');
    if (!fs.existsSync(auth)) continue;
    targets.push(path.join(home, entry.name, 'agents'));
  }

  return targets;
}

interface DiscoveredSubagent {
  name: string;
  path: string;
  source: 'plugin' | 'personal';
}

/**
 * Find Claude-format subagent `.md` files in two locations:
 *   1. `~/plugins/<plugin>/[plugins/<sub>/]agents/*.md`
 *   2. `~/.claude/agents/*.md` (personal scope)
 *
 * First-occurrence-by-name wins, with personal scope outranking plugins so a
 * user-authored override beats a plugin-shipped default. Runtime-specific
 * dirs (`.claude/`, `.cursor/`, `.codex/`, etc.) under a plugin root are
 * skipped — those are runtime-specific copies; we want the canonical
 * Claude `.md` shape only. Hidden dirs (starting with `.`) and `deprecated/`
 * dirs are skipped too.
 */
function discoverClaudeSubagents(): DiscoveredSubagent[] {
  const home = os.homedir();
  const seen = new Map<string, DiscoveredSubagent>();

  // Personal scope first — these override plugin defaults.
  const personalDir = path.join(home, '.claude', 'agents');
  if (fs.existsSync(personalDir)) {
    for (const f of fs.readdirSync(personalDir)) {
      if (!f.endsWith('.md')) continue;
      const name = f.replace(/\.md$/, '');
      seen.set(name, { name, path: path.join(personalDir, f), source: 'personal' });
    }
  }

  // Plugin tree.
  const pluginsRoot = path.join(home, 'plugins');
  if (fs.existsSync(pluginsRoot)) {
    for (const plugin of fs.readdirSync(pluginsRoot)) {
      if (plugin.startsWith('.')) continue;
      walkPluginAgents(path.join(pluginsRoot, plugin), seen);
    }
  }

  return [...seen.values()];
}

function walkPluginAgents(dir: string, seen: Map<string, DiscoveredSubagent>, depth = 0): void {
  if (depth > 3) return;
  let entries: fs.Dirent[];
  try {
    entries = fs.readdirSync(dir, { withFileTypes: true });
  } catch {
    return;
  }
  for (const entry of entries) {
    if (entry.name.startsWith('.')) continue;
    if (entry.name === 'deprecated') continue;
    if (entry.name === 'node_modules') continue;
    if (!entry.isDirectory()) continue;
    const childPath = path.join(dir, entry.name);
    if (entry.name === 'agents') {
      // Found an agents/ dir — collect every `<name>.md` here, then keep
      // walking so deeper agents/ dirs (e.g. nested sub-plugins) are still
      // discovered. First-by-name still wins overall.
      for (const file of fs.readdirSync(childPath)) {
        if (!file.endsWith('.md')) continue;
        const name = file.replace(/\.md$/, '');
        if (seen.has(name)) continue;
        seen.set(name, { name, path: path.join(childPath, file), source: 'plugin' });
      }
      continue;
    }
    walkPluginAgents(childPath, seen, depth + 1);
  }
}

interface MarketplaceJson {
  plugins?: MarketplaceEntry[];
}

interface MarketplaceEntry {
  name?: string;
  source?: {
    source?: string;
    path?: string;
  };
}

function parseTomlBlocks(content: string): ParsedTomlBlock[] {
  const blocks: ParsedTomlBlock[] = [];
  let current: ParsedTomlBlock | null = null;

  for (const line of content.split(/\r?\n/)) {
    const header = line.match(/^\s*\[([^\]]+)]\s*$/);
    if (header) {
      const parsed = parseTableHeader(header[1]);
      current = parsed;
      if (current) blocks.push(current);
      continue;
    }
    if (!current) continue;
    const kv = line.match(/^\s*([A-Za-z0-9_-]+)\s*=\s*(.*?)\s*$/);
    if (!kv) continue;
    current.values.set(kv[1], kv[2].replace(/\s+#.*$/, ''));
  }

  return blocks;
}

function parseTableHeader(raw: string): ParsedTomlBlock | null {
  const dot = raw.indexOf('.');
  if (dot < 0) return null;
  const table = raw.slice(0, dot);
  if (table !== 'marketplaces' && table !== 'plugins') return null;
  const name = tomlString(raw.slice(dot + 1)) ?? raw.slice(dot + 1);
  return { table, name, values: new Map() };
}

function tomlString(value: string | undefined): string | null {
  if (!value) return null;
  const trimmed = value.trim();
  if (trimmed.startsWith('"') && trimmed.endsWith('"')) {
    try {
      return JSON.parse(trimmed) as string;
    } catch {
      return trimmed.slice(1, -1);
    }
  }
  return trimmed;
}

function tomlBool(value: string | undefined): boolean | null {
  if (!value) return null;
  const trimmed = value.trim();
  if (trimmed === 'true') return true;
  if (trimmed === 'false') return false;
  return null;
}

function expandHome(p: string, home: string): string {
  if (p === '~') return home;
  if (p.startsWith(`~${path.sep}`)) return path.join(home, p.slice(2));
  return p;
}

function resolveMarketplaceSourceRoot(
  block: ParsedTomlBlock,
  sourceType: string,
  codexDir: string,
  home: string,
  result: CodexLocalMarketplacePluginCacheSyncResult,
): string | null {
  if (sourceType === 'local') {
    const source = tomlString(block.values.get('source'));
    if (!source) {
      result.skipped.push(`${block.name}:missing-source`);
      return null;
    }
    return path.resolve(expandHome(source, home));
  }

  const sourceRoot = path.join(codexDir, '.tmp', 'marketplaces', block.name);
  if (!fs.existsSync(sourceRoot)) {
    result.skipped.push(`${block.name}:missing-git-marketplace-cache`);
    return null;
  }
  return sourceRoot;
}

function marketplaceInstallId(block: ParsedTomlBlock): string {
  const revision = tomlString(block.values.get('last_revision'));
  if (revision) return revision.slice(0, 8);
  return 'git';
}

function isInsidePath(parent: string, child: string): boolean {
  const rel = path.relative(path.resolve(parent), path.resolve(child));
  return rel === '' || (!!rel && !rel.startsWith('..') && !path.isAbsolute(rel));
}

function replaceDirectory(source: string, target: string): void {
  const resolvedTarget = path.resolve(target);
  fs.mkdirSync(path.dirname(resolvedTarget), { recursive: true });
  fs.rmSync(resolvedTarget, { recursive: true, force: true });
  fs.cpSync(source, resolvedTarget, {
    recursive: true,
    dereference: false,
    verbatimSymlinks: true,
    filter: (src) => !src.split(path.sep).includes('.git'),
  });
}
