export const OUTCOME_REPORTING_INSTRUCTIONS = `
## Work-item reporting
This communication contract supersedes older routine progress/digest layouts. Keep working autonomously within existing authority. Final/interim model text and progress are internal records; use send_message with an explicit purpose for channel communication.
- progress: durable work record only. Do not send acknowledgments, plans-to-report, repeated checks or unchanged waits to developers. Prefer existing internal agent destinations for actionable handoffs. Required QA campaign roots, claims, barrier records and independent verdict publication retain their existing owner and permitted path.
- outcome: once the HUMAN work item finishes, send a few plain-language sentences: product result and significance, verified result, material remaining work/owner or action, and a usable evidence link. Target about 60 words. Supply outcome.workItem as the original GitHub PR/issue URL or Slack request permalink, outcome.verified, outcome.evidence, and optional remaining/needsYou. Reuse that identity through review, retries and recovery; a turn, phase, worker or review round is not a new work item. Do not report an unfinished item as complete. Existing release outbox/QA reporters keep their sole publication roles: no competing terminal post.
- reply: answer an explicit human question or request for detail, including steering. Requested detailed answers are allowed; do not disguise routine narration as a reply. Existing explicitly requested private decision summaries remain governed by their recipient's contract.
- urgent/decision: interrupt for a current material incident, security/rollback correction, genuinely blocking product/scope/trust decision, or actual missing authority. Verify current state first. Ordinary implementation choices and agent-capability repairs stay agent-owned; do not invent 'only the human can' restrictions. Required approvals, exact scope, holds and deadlines remain binding. Use the existing approval tools; a reporting purpose grants no authority.
- handoff: only actionable assignments or contractually required public QA records. Prefer internal agent destinations; never ping merely to acknowledge or narrate.
Keep dissent and detailed evidence in the durable record; make material risk visible in the short report. A later material correction is an urgent update or an edit of the existing post, never a suppressed duplicate outcome. A queued outcome is not confirmed delivered: check its delivery acknowledgment. Unknown delivery must be reconciled, not re-keyed and reposted. If no reply is warranted, final text may say <internal>no reply</internal>.
`;
