/**
 * GENERATED by scripts/vendor-workflow-agent.ts from the bootstrap plugin's
 * plugins/workflow/worker-policy.json. Do not edit — edit the policy in ~/plugins/bootstrap,
 * push it, then re-run the vendor script here (docs/review-policy.md,
 * "Changing the worker policy").
 *
 * Why a generated constant and not a config read: the values must be present in
 * a fresh clone with no plugin repo (CI, a container image build), and they must
 * be fingerprinted, so that an in-tree edit fails a test instead of silently
 * changing what every agent container dispatches.
 */

/** The frontier worker's Codex model — what `worker-frontier` dispatches to. */
export const WORKER_POLICY_CODEX_MODEL = 'gpt-5.6-sol';

/**
 * The frontier worker's Codex reasoning effort. Codex named roles have no
 * per-role effort field, so this lands as
 * `[agents].default_subagent_reasoning_effort` in the container's config.toml —
 * a GLOBAL subagent default, which a native spawn's own `reasoning_effort`
 * still overrides per task.
 */
export const WORKER_POLICY_CODEX_EFFORT = 'high';

/** The frontier worker's Claude model, as the plugin's agent def pins it. */
export const WORKER_POLICY_CLAUDE_MODEL = 'claude-opus-5[1m]';

/** The frontier worker's Claude effort, as the plugin's agent def pins it. */
export const WORKER_POLICY_CLAUDE_EFFORT = 'high';
